<a href="https://colab.research.google.com/github/ynlare/BIRTH/blob/main/Collected_data_from_the_bank_statement_for_Collection_Financial_Standards.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
# https://www.youtube.com/watch?v=IJQ59qxzMso
#Python & SQLite: Backup DB & Delete, Drop Table
#https://www.youtube.com/watch?v=IJQ59qxzMso&list=PLyOUQoTGhu3iET4UTMdLpzskFeZIA73rj&index=5
#Spark - How to Execute SQL query on DataFrame | Spark Tutorial | Part 16
#Setting up PySpark 3.0 on Google Colab for FREE | Part 1 | Hands-On | Data Making | DM | DataMaking
#https://www.nbshare.io/

# **Collected data from the bank statement for Collection Financial Standards**

# Project Description: (Data Engineer Roles and Responsibilities)
# 1.Convert erroneous data into a usable form for further analysis.
# 2.Create large data warehouses using ETL.
# 3.Develop, test, and maintain architectures.
# 4.Develop dataset processes.

In [78]:
#Collection Financial Standards are used to help determine a taxpayer's ability to pay a delinquent tax liability. Allowable living expenses include those expenses that meet the necessary expense test.

In [79]:
!pip install csv
import pandas as pd
from pandas import DataFrame
from typing import List
from datetime import datetime
import csv
from google.colab import files
from google.colab import drive
!pip install openpyxl
!install urllib
import urllib
from google.colab import drive
drive.mount('/content/drive')
!install seaborn
!install matplotlib
from IPython import display
!pip install numpy 
import numpy as np
!pip install os
import os
!pip install pyspark
!pip install -U pyarrow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement csv (from versions: none)
ERROR: No matching distribution found for csv
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: openpyxl in /usr/local/lib/python3.8/dist-packages (3.0.10)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.8/dist-packages (from openpyxl) (1.1.0)
install: missing destination file operand after 'urllib'
Try 'install --help' for more information.
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
install: missing destination file operand after 'seaborn'
Try 'install --help' for more information.
install: missing destination file operand after 'matplotlib'
Try 'install --help' for more information.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (1.21.6)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement os (from versions: none)
ERROR: No matching distribution found for os
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pyspark in /usr/local/lib/python3.8/dist-packages (3.3.1)
Requirement already satisfied: py4j==0.10.9.5 in /usr/local/lib/python3.8/dist-packages (from pyspark) (0.10.9.5)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pyarrow in /usr/local/lib/python3.8/dist-packages (11.0.0)
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.8/dist-packages (from pyarrow) (1.21.6)

In [80]:
!python --version

Python 3.8.10

In [81]:
#Install the latest version of Apache Spark:
#!pip install pyspark
#Install findspark library to locate Spark:
#!pip install findspark
#Start a Spark session:
#import findspark
#findspark.init()
#from pyspark.sql import SparkSession
#spark = SparkSession.builder.appName("Spark_Example").getOrCreate()

In [82]:
#!apt-get install openjdk-8-jdk-headless -qq > /dev/null
#!tar xf spark-3.1.2-bin-hadoop2.7.tgz

In [83]:
!pwd
!wget https://dlcdn.apache.org/spark/spark-3.3.1/spark-3.3.1-bin-hadoop3.tgz

/content
--2023-02-01 05:46:06--  https://dlcdn.apache.org/spark/spark-3.3.1/spark-3.3.1-bin-hadoop3.tgz
Resolving dlcdn.apache.org (dlcdn.apache.org)... 151.101.2.132, 2a04:4e42::644
Connecting to dlcdn.apache.org (dlcdn.apache.org)|151.101.2.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 299350810 (285M) [application/x-gzip]
Saving to: ‘spark-3.3.1-bin-hadoop3.tgz.1’

spark-3.3.1-bin-had 100%[===================>] 285.48M   209MB/s    in 1.4s

2023-02-01 05:46:07 (209 MB/s) - ‘spark-3.3.1-bin-hadoop3.tgz.1’ saved [299350810/299350810]

In [84]:
!tar -xvzf spark-3.3.1-bin-hadoop3.tgz

spark-3.3.1-bin-hadoop3/
spark-3.3.1-bin-hadoop3/LICENSE
spark-3.3.1-bin-hadoop3/NOTICE
spark-3.3.1-bin-hadoop3/R/
spark-3.3.1-bin-hadoop3/R/lib/
spark-3.3.1-bin-hadoop3/R/lib/SparkR/
spark-3.3.1-bin-hadoop3/R/lib/SparkR/DESCRIPTION
spark-3.3.1-bin-hadoop3/R/lib/SparkR/INDEX
spark-3.3.1-bin-hadoop3/R/lib/SparkR/Meta/
spark-3.3.1-bin-hadoop3/R/lib/SparkR/Meta/Rd.rds
spark-3.3.1-bin-hadoop3/R/lib/SparkR/Meta/features.rds
spark-3.3.1-bin-hadoop3/R/lib/SparkR/Meta/hsearch.rds
spark-3.3.1-bin-hadoop3/R/lib/SparkR/Meta/links.rds
spark-3.3.1-bin-hadoop3/R/lib/SparkR/Meta/nsInfo.rds
spark-3.3.1-bin-hadoop3/R/lib/SparkR/Meta/package.rds
spark-3.3.1-bin-hadoop3/R/lib/SparkR/Meta/vignette.rds
spark-3.3.1-bin-hadoop3/R/lib/SparkR/NAMESPACE
spark-3.3.1-bin-hadoop3/R/lib/SparkR/R/
spark-3.3.1-bin-hadoop3/R/lib/SparkR/R/SparkR
spark-3.3.1-bin-hadoop3/R/lib/SparkR/R/SparkR.rdb
spark-3.3.1-bin-hadoop3/R/lib/SparkR/R/SparkR.rdx
spark-3.3.1-bin-hadoop3/R/lib/SparkR/doc/
spark-3.3.1-bin-hadoop3/R/lib/SparkR/doc/index.html
spark-3.3.1-bin-hadoop3/R/lib/SparkR/doc/sparkr-vignettes.R
spark-3.3.1-bin-hadoop3/R/lib/SparkR/doc/sparkr-vignettes.Rmd
spark-3.3.1-bin-hadoop3/R/lib/SparkR/doc/sparkr-vignettes.html
spark-3.3.1-bin-hadoop3/R/lib/SparkR/help/
spark-3.3.1-bin-hadoop3/R/lib/SparkR/help/AnIndex
spark-3.3.1-bin-hadoop3/R/lib/SparkR/help/SparkR.rdb
spark-3.3.1-bin-hadoop3/R/lib/SparkR/help/SparkR.rdx
spark-3.3.1-bin-hadoop3/R/lib/SparkR/help/aliases.rds
spark-3.3.1-bin-hadoop3/R/lib/SparkR/help/paths.rds
spark-3.3.1-bin-hadoop3/R/lib/SparkR/html/
spark-3.3.1-bin-hadoop3/R/lib/SparkR/html/00Index.html
spark-3.3.1-bin-hadoop3/R/lib/SparkR/html/R.css
spark-3.3.1-bin-hadoop3/R/lib/SparkR/profile/
spark-3.3.1-bin-hadoop3/R/lib/SparkR/profile/general.R
spark-3.3.1-bin-hadoop3/R/lib/SparkR/profile/shell.R
spark-3.3.1-bin-hadoop3/R/lib/SparkR/tests/
spark-3.3.1-bin-hadoop3/R/lib/SparkR/tests/testthat/
spark-3.3.1-bin-hadoop3/R/lib/SparkR/tests/testthat/test_basic.R
spark-3.3.1-bin-hadoop3/R/lib/SparkR/worker/
spark-3.3.1-bin-hadoop3/R/lib/SparkR/worker/daemon.R
spark-3.3.1-bin-hadoop3/R/lib/SparkR/worker/worker.R
spark-3.3.1-bin-hadoop3/R/lib/sparkr.zip
spark-3.3.1-bin-hadoop3/README.md
spark-3.3.1-bin-hadoop3/RELEASE
spark-3.3.1-bin-hadoop3/bin/
spark-3.3.1-bin-hadoop3/bin/beeline
spark-3.3.1-bin-hadoop3/bin/beeline.cmd
spark-3.3.1-bin-hadoop3/bin/docker-image-tool.sh
spark-3.3.1-bin-hadoop3/bin/find-spark-home
spark-3.3.1-bin-hadoop3/bin/find-spark-home.cmd
spark-3.3.1-bin-hadoop3/bin/load-spark-env.cmd
spark-3.3.1-bin-hadoop3/bin/load-spark-env.sh
spark-3.3.1-bin-hadoop3/bin/pyspark
spark-3.3.1-bin-hadoop3/bin/pyspark.cmd
spark-3.3.1-bin-hadoop3/bin/pyspark2.cmd
spark-3.3.1-bin-hadoop3/bin/run-example
spark-3.3.1-bin-hadoop3/bin/run-example.cmd
spark-3.3.1-bin-hadoop3/bin/spark-class
spark-3.3.1-bin-hadoop3/bin/spark-class.cmd
spark-3.3.1-bin-hadoop3/bin/spark-class2.cmd
spark-3.3.1-bin-hadoop3/bin/spark-shell
spark-3.3.1-bin-hadoop3/bin/spark-shell.cmd
spark-3.3.1-bin-hadoop3/bin/spark-shell2.cmd
spark-3.3.1-bin-hadoop3/bin/spark-sql
spark-3.3.1-bin-hadoop3/bin/spark-sql.cmd
spark-3.3.1-bin-hadoop3/bin/spark-sql2.cmd
spark-3.3.1-bin-hadoop3/bin/spark-submit
spark-3.3.1-bin-hadoop3/bin/spark-submit.cmd
spark-3.3.1-bin-hadoop3/bin/spark-submit2.cmd
spark-3.3.1-bin-hadoop3/bin/sparkR
spark-3.3.1-bin-hadoop3/bin/sparkR.cmd
spark-3.3.1-bin-hadoop3/bin/sparkR2.cmd
spark-3.3.1-bin-hadoop3/conf/
spark-3.3.1-bin-hadoop3/conf/fairscheduler.xml.template
spark-3.3.1-bin-hadoop3/conf/log4j2.properties.template
spark-3.3.1-bin-hadoop3/conf/metrics.properties.template
spark-3.3.1-bin-hadoop3/conf/spark-defaults.conf.template
spark-3.3.1-bin-hadoop3/conf/spark-env.sh.template
spark-3.3.1-bin-hadoop3/conf/workers.template
spark-3.3.1-bin-hadoop3/data/
spark-3.3.1-bin-hadoop3/data/graphx/
spark-3.3.1-bin-hadoop3/data/graphx/followers.txt
spark-3.3.1-bin-hadoop3/data/graphx/users.txt
spark-3.3.1-bin-hadoop3/data/mllib/
spark-3.3.1-bin-hadoop3/data/mllib/als/
spark-3.3.1-bin-hadoop3/data/mllib/als/sample_movielens_ratings.txt
spark-3.3.1-bin-hadoop3/data/mllib/als/test.data
spark-3.3.1-bin-hadoop3/data/mllib/gmm_data.txt
spark-3.3.1-bin-hadoop3/data/mllib/images/
spark-3.3.1-bin-hadoop3/data/mllib/images/license.txt
spark-3.3.1-bin-hadoop3/data/mllib/images/origin/
spark-3.3.1-bin-hadoop3/data/mllib/images/origin/kittens/
spark-3.3.1-bin-hadoop3/data/mllib/images/origin/kittens/29.5.a_b_EGDP022204.jpg
spark-3.3.1-bin-hadoop3/data/mllib/images/origin/kittens/54893.jpg
spark-3.3.1-bin-hadoop3/data/mllib/images/origin/kittens/DP153539.jpg
spark-3.3.1-bin-hadoop3/data/mllib/images/origin/kittens/DP802813.jpg
spark-3.3.1-bin-hadoop3/data/mllib/images/origin/kittens/not-image.txt
spark-3.3.1-bin-hadoop3/data/mllib/images/origin/license.txt
spark-3.3.1-bin-hadoop3/data/mllib/images/origin/multi-channel/
spark-3.3.1-bin-hadoop3/data/mllib/images/origin/multi-channel/BGRA.png
spark-3.3.1-bin-hadoop3/data/mllib/images/origin/multi-channel/BGRA_alpha_60.png
spark-3.3.1-bin-hadoop3/data/mllib/images/origin/multi-channel/chr30.4.184.jpg
spark-3.3.1-bin-hadoop3/data/mllib/images/origin/multi-channel/grayscale.jpg
spark-3.3.1-bin-hadoop3/data/mllib/kmeans_data.txt
spark-3.3.1-bin-hadoop3/data/mllib/pagerank_data.txt
spark-3.3.1-bin-hadoop3/data/mllib/pic_data.txt
spark-3.3.1-bin-hadoop3/data/mllib/ridge-data/
spark-3.3.1-bin-hadoop3/data/mllib/ridge-data/lpsa.data
spark-3.3.1-bin-hadoop3/data/mllib/sample_binary_classification_data.txt
spark-3.3.1-bin-hadoop3/data/mllib/sample_fpgrowth.txt
spark-3.3.1-bin-hadoop3/data/mllib/sample_isotonic_regression_libsvm_data.txt
spark-3.3.1-bin-hadoop3/data/mllib/sample_kmeans_data.txt
spark-3.3.1-bin-hadoop3/data/mllib/sample_lda_data.txt
spark-3.3.1-bin-hadoop3/data/mllib/sample_lda_libsvm_data.txt
spark-3.3.1-bin-hadoop3/data/mllib/sample_libsvm_data.txt
spark-3.3.1-bin-hadoop3/data/mllib/sample_linear_regression_data.txt
spark-3.3.1-bin-hadoop3/data/mllib/sample_movielens_data.txt
spark-3.3.1-bin-hadoop3/data/mllib/sample_multiclass_classification_data.txt
spark-3.3.1-bin-hadoop3/data/mllib/sample_svm_data.txt
spark-3.3.1-bin-hadoop3/data/mllib/streaming_kmeans_data_test.txt
spark-3.3.1-bin-hadoop3/data/streaming/
spark-3.3.1-bin-hadoop3/data/streaming/AFINN-111.txt
spark-3.3.1-bin-hadoop3/examples/
spark-3.3.1-bin-hadoop3/examples/jars/
spark-3.3.1-bin-hadoop3/examples/jars/scopt_2.12-3.7.1.jar
spark-3.3.1-bin-hadoop3/examples/jars/spark-examples_2.12-3.3.1.jar
spark-3.3.1-bin-hadoop3/examples/src/
spark-3.3.1-bin-hadoop3/examples/src/main/
spark-3.3.1-bin-hadoop3/examples/src/main/java/
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaHdfsLR.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaLogQuery.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaPageRank.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaSparkPi.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaStatusTrackerDemo.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaTC.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaWordCount.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaAFTSurvivalRegressionExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaALSExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaBinarizerExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaBisectingKMeansExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaBucketedRandomProjectionLSHExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaBucketizerExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaChiSqSelectorExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaChiSquareTestExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaCorrelationExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaCountVectorizerExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaDCTExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaDecisionTreeClassificationExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaDecisionTreeRegressionExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaDocument.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaElementwiseProductExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaEstimatorTransformerParamExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaFMClassifierExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaFMRegressorExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaFPGrowthExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaFeatureHasherExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaGaussianMixtureExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaGeneralizedLinearRegressionExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaGradientBoostedTreeClassifierExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaGradientBoostedTreeRegressorExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaImputerExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaIndexToStringExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaInteractionExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaIsotonicRegressionExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaKMeansExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaLDAExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaLabeledDocument.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaLinearRegressionWithElasticNetExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaLinearSVCExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaLogisticRegressionSummaryExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaLogisticRegressionWithElasticNetExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaMaxAbsScalerExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaMinHashLSHExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaMinMaxScalerExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaModelSelectionViaCrossValidationExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaModelSelectionViaTrainValidationSplitExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaMulticlassLogisticRegressionWithElasticNetExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaMultilayerPerceptronClassifierExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaNGramExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaNaiveBayesExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaNormalizerExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaOneHotEncoderExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaOneVsRestExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaPCAExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaPipelineExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaPolynomialExpansionExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaPowerIterationClusteringExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaPrefixSpanExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaQuantileDiscretizerExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaRFormulaExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaRandomForestClassifierExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaRandomForestRegressorExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaRobustScalerExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaSQLTransformerExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaStandardScalerExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaStopWordsRemoverExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaStringIndexerExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaSummarizerExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaTfIdfExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaTokenizerExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaUnivariateFeatureSelectorExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaVarianceThresholdSelectorExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorAssemblerExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorIndexerExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorSizeHintExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorSlicerExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaWord2VecExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaALS.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaAssociationRulesExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaBinaryClassificationMetricsExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaBisectingKMeansExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaChiSqSelectorExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaCorrelationsExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaDecisionTreeClassificationExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaDecisionTreeRegressionExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaElementwiseProductExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaGaussianMixtureExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaGradientBoostingClassificationExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaGradientBoostingRegressionExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaHypothesisTestingExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaHypothesisTestingKolmogorovSmirnovTestExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaIsotonicRegressionExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaKMeansExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaKernelDensityEstimationExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaLBFGSExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaLatentDirichletAllocationExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaLogisticRegressionWithLBFGSExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaMultiLabelClassificationMetricsExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaMulticlassClassificationMetricsExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaNaiveBayesExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaPCAExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaPowerIterationClusteringExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaPrefixSpanExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaRandomForestClassificationExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaRandomForestRegressionExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaRankingMetricsExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaRecommendationExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaSVDExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaSVMWithSGDExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaSimpleFPGrowth.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaStratifiedSamplingExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaStreamingTestExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaSummaryStatisticsExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/sql/
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/sql/JavaSQLDataSourceExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/sql/JavaSparkSQLExample.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/sql/JavaUserDefinedScalar.java
spark-3.3.1-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/sql/JavaUserDefinedTypedAggregation.java

In [85]:
!ls /content/spark-3.3.1-bin-hadoop3
!pip install findspark

bin   data	jars	    LICENSE   NOTICE  R		 RELEASE  yarn
conf  examples	kubernetes  licenses  python  README.md  sbin
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: findspark in /usr/local/lib/python3.8/dist-packages (2.0.1)

In [86]:
import os
os.environ["SPARK_HOME"] = "/content/spark-3.3.1-bin-hadoop3"
#os.environ["SPARK_HOME"] = "/content/spark-3.1.2-bin-hadoop2.7"

In [87]:
#!pip install -q findspark
import findspark
findspark.init()
#!pip install pyspark

In [88]:
findspark.find()

'/content/spark-3.3.1-bin-hadoop3'

In [89]:
from pyspark.sql import SparkSession

In [90]:
spark = SparkSession.builder.appName("CSV_Processing_with PySpark").getOrCreate()

In [91]:
#path = "/content/drive/MyDrive/Data_Engineering/Raw_Card_Transaction_Data_Processing/Transaction_Data_ouput - Sheet1.csv"

In [92]:
#Raw_data = spark.read.option("header",'True'). option('delimiter', "|"). csv(path)
#Raw_data = spark.read.option("header",'True'). csv(path)
Raw_data =  pd.read_excel("/content/drive/MyDrive/Data_Engineering/Raw_Card_Transaction_Data_Processing/Raw_card_transaction_data.xlsx")

In [93]:
Raw_data

,Description,Withdrawals/\nSubtractions
0,Purchase authorized on 12/05 Qt 296 Inside Len...,6.42
1,Purchase authorized on 12/06 Qt 243 Overland P...,5.31
2,Purchase authorized on 12/06 Cafe Santa Fe Ove...,4.93
3,Purchase authorized on 12/06 Qt 296 Inside Len...,2.07
4,Purchase authorized on 12/06 Paypal *Udemy 888...,11.99
...,...,...
1350,Purchase authorized on 02/05 Tst* Str-Eatz Kan...,13.00
1351,Purchase authorized on 02/05 Bobka LLC Kansas ...,13.00
1352,Purchase authorized on 02/05 Qt 233 Belton MO\...,10.00
1353,Purchase authorized on 02/06 Caseys Lenexa 999...,17.62
1354,Interest Payment,NaN

In [94]:
newdf = Raw_data.copy()

newdf

,Description,Withdrawals/\nSubtractions
0,Purchase authorized on 12/05 Qt 296 Inside Len...,6.42
1,Purchase authorized on 12/06 Qt 243 Overland P...,5.31
2,Purchase authorized on 12/06 Cafe Santa Fe Ove...,4.93
3,Purchase authorized on 12/06 Qt 296 Inside Len...,2.07
4,Purchase authorized on 12/06 Paypal *Udemy 888...,11.99
...,...,...
1350,Purchase authorized on 02/05 Tst* Str-Eatz Kan...,13.00
1351,Purchase authorized on 02/05 Bobka LLC Kansas ...,13.00
1352,Purchase authorized on 02/05 Qt 233 Belton MO\...,10.00
1353,Purchase authorized on 02/06 Caseys Lenexa 999...,17.62
1354,Interest Payment,NaN

In [95]:
# Convert Pandas dataframe to PySpark dataframe
spark_df = spark.createDataFrame(newdf)

In [96]:
spark_df.printSchema()

root
 |-- Description: string (nullable = true)
 |-- Withdrawals/\nSubtractions: double (nullable = true)

In [97]:
# get the Description : "Purchase authorized on" from dataframe
#spark_df.filter((spark_df.Description).isin('Purchase authorized on'))
############

In [98]:
First_filter = spark_df.filter((spark_df.Description).like("Purchase authorized on%"))
First_filter.show(truncate=False)
##########

+----------------------------------------------------------------------------------------------+--------------------------+
|Description                                                                                   |Withdrawals/\nSubtractions|
+----------------------------------------------------------------------------------------------+--------------------------+
|Purchase authorized on 12/05 Qt 296 Inside Lenexa KS\nS582340165832738 Card 3691              |6.42                      |
|Purchase authorized on 12/06 Qt 243 Overland Park KS\nS462340609044917 Card 3691              |5.31                      |
|Purchase authorized on 12/06 Cafe Santa Fe Overland Park KS\nS382340641677396 Card 3691       |4.93                      |
|Purchase authorized on 12/06 Qt 296 Inside Lenexa KS\nS382341149520841 Card 3691              |2.07                      |
|Purchase authorized on 12/06 Paypal *Udemy 888-838-5432 CA\nS382341176020450 Card 3691        |11.99                     |
|Purchase authorized on 12/07 Qt 243 Overland Park KS\nS302341594330371 Card 3691              |2.06                      |
|Purchase authorized on 12/08 McDonald's F10543 Overland Park\nKS S302342585515540 Card 3691   |6.2                       |
|Purchase authorized on 12/08 Superior Mini M Kansas City MO\nP000000785427678 Card 3691       |20.0                      |
|Purchase authorized on 12/09 Ross Stores #1696 Overland Park\nKS P000000281059471 Card 3691   |91.31                     |
|Purchase authorized on 12/09 Mk Beauty Supply LLC Overland\nPark KS P302343607792757 Card 3691|13.62                     |
|Purchase authorized on 12/07 Qt 296 Inside Lenexa KS\nS582342188766791 Card 3691              |2.38                      |
|Purchase authorized on 12/07 Qt 296 Inside Lenexa KS\nS462342189113701 Card 3691              |2.6                       |
|Purchase authorized on 12/08 Qt 296 Inside Lenexa KS\nS582343123191010 Card 3691              |4.67                      |
|Purchase authorized on 12/09 Qt 182 Olathe KS\nS382343537877793 Card 3691                     |5.55                      |
|Purchase authorized on 12/09 Cafe Santa Fe Overland Park KS\nS582343730583343 Card 3691       |10.96                     |
|Purchase authorized on 12/09 Goodcents Subs - 0 Lenexa KS\nS462343805639077 Card 3691         |13.12                     |
|Purchase authorized on 12/09 Starbucks Store 25 Overland Park\nKS S302343826658285 Card 3691  |3.55                      |
|Purchase authorized on 12/09 Qt 243 Inside Overland Park KS\nP462344133700849 Card 3691       |22.06                     |
|Purchase authorized on 12/10 Qt 206 Olathe KS\nS582344602606138 Card 3691                     |5.44                      |
|Purchase authorized on 12/10 Mariscos Kc Olathe KS\nS582344730933940 Card 3691                |23.97                     |
+----------------------------------------------------------------------------------------------+--------------------------+
only showing top 20 rows

In [99]:
#df_pandas_First_filter= First_filter.toPandas()
#df_pandas_First_filter

In [100]:
!pip install selectExpr
from pyspark.sql.functions import split

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement selectExpr (from versions: none)
ERROR: No matching distribution found for selectExpr

In [101]:
#First_filterSplit1 = First_filter.withColumn('Store_Address_Description', split(First_filter['Description '], '\').getItem(1))\
                                 # .withColumn('Identification', split(First_filter['Description '], '\').getItem(1))

In [102]:
#First_filterSplit1 = First_filter.withColumn('Store_Address_Description', split(First_filter['Description'], '\\').getItem(0))\
                                 # .withColumn('Identification', split(First_filter['Description'], '\\').getItem(1))

#First_filterSplit1.show()

In [103]:
#First_filterSplit1 = First_filter.withColumn('Store_Address_Description', split(First_filter['Description'], '\\')[0])\
                                # .withColumn('Identification', split(First_filter['Description'], '\\')[1])
#First_filterSplit1.show()

In [104]:
#df_pandas_First_filterSplit1= First_filterSplit1.toPandas()
#df_pandas_First_filterSplit1

In [105]:
First_filter_drop_na = First_filter.na.drop()
First_filter_drop_na.show(truncate=False)

+----------------------------------------------------------------------------------------------+--------------------------+
|Description                                                                                   |Withdrawals/\nSubtractions|
+----------------------------------------------------------------------------------------------+--------------------------+
|Purchase authorized on 12/05 Qt 296 Inside Lenexa KS\nS582340165832738 Card 3691              |6.42                      |
|Purchase authorized on 12/06 Qt 243 Overland Park KS\nS462340609044917 Card 3691              |5.31                      |
|Purchase authorized on 12/06 Cafe Santa Fe Overland Park KS\nS382340641677396 Card 3691       |4.93                      |
|Purchase authorized on 12/06 Qt 296 Inside Lenexa KS\nS382341149520841 Card 3691              |2.07                      |
|Purchase authorized on 12/06 Paypal *Udemy 888-838-5432 CA\nS382341176020450 Card 3691        |11.99                     |
|Purchase authorized on 12/07 Qt 243 Overland Park KS\nS302341594330371 Card 3691              |2.06                      |
|Purchase authorized on 12/08 McDonald's F10543 Overland Park\nKS S302342585515540 Card 3691   |6.2                       |
|Purchase authorized on 12/08 Superior Mini M Kansas City MO\nP000000785427678 Card 3691       |20.0                      |
|Purchase authorized on 12/09 Ross Stores #1696 Overland Park\nKS P000000281059471 Card 3691   |91.31                     |
|Purchase authorized on 12/09 Mk Beauty Supply LLC Overland\nPark KS P302343607792757 Card 3691|13.62                     |
|Purchase authorized on 12/07 Qt 296 Inside Lenexa KS\nS582342188766791 Card 3691              |2.38                      |
|Purchase authorized on 12/07 Qt 296 Inside Lenexa KS\nS462342189113701 Card 3691              |2.6                       |
|Purchase authorized on 12/08 Qt 296 Inside Lenexa KS\nS582343123191010 Card 3691              |4.67                      |
|Purchase authorized on 12/09 Qt 182 Olathe KS\nS382343537877793 Card 3691                     |5.55                      |
|Purchase authorized on 12/09 Cafe Santa Fe Overland Park KS\nS582343730583343 Card 3691       |10.96                     |
|Purchase authorized on 12/09 Goodcents Subs - 0 Lenexa KS\nS462343805639077 Card 3691         |13.12                     |
|Purchase authorized on 12/09 Starbucks Store 25 Overland Park\nKS S302343826658285 Card 3691  |3.55                      |
|Purchase authorized on 12/09 Qt 243 Inside Overland Park KS\nP462344133700849 Card 3691       |22.06                     |
|Purchase authorized on 12/10 Qt 206 Olathe KS\nS582344602606138 Card 3691                     |5.44                      |
|Purchase authorized on 12/10 Mariscos Kc Olathe KS\nS582344730933940 Card 3691                |23.97                     |
+----------------------------------------------------------------------------------------------+--------------------------+
only showing top 20 rows

In [106]:
from pyspark.sql.functions import substring
from pyspark.sql.functions import substring, locate
from pyspark.sql.functions import substring, locate
#First_filter.withColumn("Actions", substring(col("Description")), 0, locate("\n", ((col("Description"))).cast("integer")))
df_pandas_First_filterSplit1= First_filter_drop_na.toPandas()
df_pandas_First_filterSplit1

,Description,Withdrawals/\nSubtractions
0,Purchase authorized on 12/05 Qt 296 Inside Len...,6.42
1,Purchase authorized on 12/06 Qt 243 Overland P...,5.31
2,Purchase authorized on 12/06 Cafe Santa Fe Ove...,4.93
3,Purchase authorized on 12/06 Qt 296 Inside Len...,2.07
4,Purchase authorized on 12/06 Paypal *Udemy 888...,11.99
...,...,...
1182,Purchase authorized on 02/05 McDonald's F37944...,6.09
1183,Purchase authorized on 02/05 Tst* Str-Eatz Kan...,13.00
1184,Purchase authorized on 02/05 Bobka LLC Kansas ...,13.00
1185,Purchase authorized on 02/05 Qt 233 Belton MO\...,10.00
1186,Purchase authorized on 02/06 Caseys Lenexa 999...,17.62

In [107]:
temp = df_pandas_First_filterSplit1['Description'].str.split('\n', expand=True)
temp.columns = ['Descriptions', 'initials']
df_pandas_First_filterSplit1 = df_pandas_First_filterSplit1.join(temp)

In [153]:
# Extract characters or a word or useful information from the Initials column.
df_initials = df_pandas_First_filterSplit1
# Iterate over the values in the "initials" column
for i in df_initials['initials']:
    if i is None:
        print('')
    elif 'Park KS' in i:
        print('Park KS')
    elif 'KS' in i:
        print('KS')
    else:
        print('')

KS

KS
Park KS






KS





KS

















KS
KS


KS



KS


KS


KS











KS








KS











































































KS









Park KS


KS






KS








Park KS




KS

















KS
KS






















KS
















Park KS











KS



Park KS









KS
KS



KS










KS



Park KS




Park KS
KS
Park KS

KS


















KS





KS






KS
KS















KS











Park KS


KS



KS













KS
KS














KS





Park KS

KS












KS
KS







KS


KS
KS













KS
KS
KS



KS


KS



KS


KS

KS





KS
KS


KS
Park KS

KS
KS





KS



KS



KS













KS
KS

KS


KS


KS



KS


KS



KS



KS
KS







KS
KS



KS





KS



KS
KS






KS


KS




KS







KS
KS






KS


KS




KS





KS
KS
Park KS

KS

Park KS
Park KS






KS

KS



















KS

KS





KS
KS

KS











Park KS
KS
KS
KS
KS


KS




KS



KS
Park KS





KS

KS





KS



KS





KS




KS
KS

KS


KS


Park KS


KS

KS


KS

KS


KS



KS



KS
Park KS

KS


KS


KS




KS
KS

KS



KS



KS

KS
KS
KS






KS





KS



KS




KS
KS
KS





KS


KS

KS








KS



KS


KS







KS




KS

KS








KS




KS


KS
















KS






























KS
KS





KS
KS


KS

KS
KS















KS

KS
KS
KS



KS





Park KS

KS
Park KS












KS

KS








KS





KS



KS

KS








KS





KS



Park KS



KS





KS
Park KS



KS






KS



KS



KS










KS
Park KS


KS







KS
KS
KS

















KS





KS



KS
KS
KS









KS






KS
Park KS




KS

KS
KS


KS







KS
KS
KS
KS

KS


KS


KS
KS



KS
KS


KS
Park KS
KS


KS
KS


Park KS
Park KS


Park KS
KS
Park KS
Park KS







KS



KS



KS




KS


KS



KS



KS

In [155]:
# You can create a new column in the dataframe and assign the output of the loop to it. 
df_initials['initials2'] = ['' if i is None else 'Park KS' if 'Park KS' in i else 'KS' if 'KS' in i else '' for i in df_initials['initials']]

In [156]:
df_initials['initials2'] # Print the column values ​​to check if it works.

0
1
2
3
4
        ..
1182    KS
1183
1184
1185
1186    KS
Name: initials2, Length: 1187, dtype: object

In [ ]:
# You can create a new column in the  principal or orginal dataframe and assign the output of the loop to it.

In [157]:
df_pandas_First_filterSplit1['initials2'] = ['' if i is None else 'Park KS' if 'Park KS' in i else 'KS' if 'KS' in i else '' for i in df_initials['initials']]

In [158]:
df_pandas_First_filterSplit1_SPARK1 = spark.createDataFrame(df_pandas_First_filterSplit1)
df_pandas_First_filterSplit1_SPARK1.show(truncate=False)

+----------------------------------------------------------------------------------------------+--------------------------+-------------------------------------------------------------+----------------------------------+---------+
|Description                                                                                   |Withdrawals/\nSubtractions|Descriptions                                                 |initials                          |initials2|
+----------------------------------------------------------------------------------------------+--------------------------+-------------------------------------------------------------+----------------------------------+---------+
|Purchase authorized on 12/05 Qt 296 Inside Lenexa KS\nS582340165832738 Card 3691              |6.42                      |Purchase authorized on 12/05 Qt 296 Inside Lenexa KS         |S582340165832738 Card 3691        |         |
|Purchase authorized on 12/06 Qt 243 Overland Park KS\nS462340609044917 Card 3691              |5.31                      |Purchase authorized on 12/06 Qt 243 Overland Park KS         |S462340609044917 Card 3691        |         |
|Purchase authorized on 12/06 Cafe Santa Fe Overland Park KS\nS382340641677396 Card 3691       |4.93                      |Purchase authorized on 12/06 Cafe Santa Fe Overland Park KS  |S382340641677396 Card 3691        |         |
|Purchase authorized on 12/06 Qt 296 Inside Lenexa KS\nS382341149520841 Card 3691              |2.07                      |Purchase authorized on 12/06 Qt 296 Inside Lenexa KS         |S382341149520841 Card 3691        |         |
|Purchase authorized on 12/06 Paypal *Udemy 888-838-5432 CA\nS382341176020450 Card 3691        |11.99                     |Purchase authorized on 12/06 Paypal *Udemy 888-838-5432 CA   |S382341176020450 Card 3691        |         |
|Purchase authorized on 12/07 Qt 243 Overland Park KS\nS302341594330371 Card 3691              |2.06                      |Purchase authorized on 12/07 Qt 243 Overland Park KS         |S302341594330371 Card 3691        |         |
|Purchase authorized on 12/08 McDonald's F10543 Overland Park\nKS S302342585515540 Card 3691   |6.2                       |Purchase authorized on 12/08 McDonald's F10543 Overland Park |KS S302342585515540 Card 3691     |KS       |
|Purchase authorized on 12/08 Superior Mini M Kansas City MO\nP000000785427678 Card 3691       |20.0                      |Purchase authorized on 12/08 Superior Mini M Kansas City MO  |P000000785427678 Card 3691        |         |
|Purchase authorized on 12/09 Ross Stores #1696 Overland Park\nKS P000000281059471 Card 3691   |91.31                     |Purchase authorized on 12/09 Ross Stores #1696 Overland Park |KS P000000281059471 Card 3691     |KS       |
|Purchase authorized on 12/09 Mk Beauty Supply LLC Overland\nPark KS P302343607792757 Card 3691|13.62                     |Purchase authorized on 12/09 Mk Beauty Supply LLC Overland   |Park KS P302343607792757 Card 3691|Park KS  |
|Purchase authorized on 12/07 Qt 296 Inside Lenexa KS\nS582342188766791 Card 3691              |2.38                      |Purchase authorized on 12/07 Qt 296 Inside Lenexa KS         |S582342188766791 Card 3691        |         |
|Purchase authorized on 12/07 Qt 296 Inside Lenexa KS\nS462342189113701 Card 3691              |2.6                       |Purchase authorized on 12/07 Qt 296 Inside Lenexa KS         |S462342189113701 Card 3691        |         |
|Purchase authorized on 12/08 Qt 296 Inside Lenexa KS\nS582343123191010 Card 3691              |4.67                      |Purchase authorized on 12/08 Qt 296 Inside Lenexa KS         |S582343123191010 Card 3691        |         |
|Purchase authorized on 12/09 Qt 182 Olathe KS\nS382343537877793 Card 3691                     |5.55                      |Purchase authorized on 12/09 Qt 182 Olathe KS                |S382343537877793 Card 3691        |         |
|Purchase authorized on 12/09 Cafe Santa Fe Overland Park KS\nS582343730583343 Card 3691       |10.96                     |Purchase authorized on 12/09 Cafe Santa Fe Overland Park KS  |S582343730583343 Card 3691        |         |
|Purchase authorized on 12/09 Goodcents Subs - 0 Lenexa KS\nS462343805639077 Card 3691         |13.12                     |Purchase authorized on 12/09 Goodcents Subs - 0 Lenexa KS    |S462343805639077 Card 3691        |         |
|Purchase authorized on 12/09 Starbucks Store 25 Overland Park\nKS S302343826658285 Card 3691  |3.55                      |Purchase authorized on 12/09 Starbucks Store 25 Overland Park|KS S302343826658285 Card 3691     |KS       |
|Purchase authorized on 12/09 Qt 243 Inside Overland Park KS\nP462344133700849 Card 3691       |22.06                     |Purchase authorized on 12/09 Qt 243 Inside Overland Park KS  |P462344133700849 Card 3691        |         |
|Purchase authorized on 12/10 Qt 206 Olathe KS\nS582344602606138 Card 3691                     |5.44                      |Purchase authorized on 12/10 Qt 206 Olathe KS                |S582344602606138 Card 3691        |         |
|Purchase authorized on 12/10 Mariscos Kc Olathe KS\nS582344730933940 Card 3691                |23.97                     |Purchase authorized on 12/10 Mariscos Kc Olathe KS           |S582344730933940 Card 3691        |         |
+----------------------------------------------------------------------------------------------+--------------------------+-------------------------------------------------------------+----------------------------------+---------+
only showing top 20 rows

In [188]:
from pyspark.sql.functions import concat, lit
df_pandas_First_filterSplit1_SPARK1 = df_pandas_First_filterSplit1_SPARK1.withColumn("New_Description", concat(df_pandas_First_filterSplit1_SPARK1["Descriptions"], lit(" "), df_pandas_First_filterSplit1_SPARK1["initials2"]))

In [189]:
df_pandas_First_filterSplit1_SPARK1.show(truncate=False)

+----------------------------------------------------------------------------------------------+--------------------------+-------------------------------------------------------------+----------------------------------+---------+------------------------------------------------------------------+
|Description                                                                                   |Withdrawals/\nSubtractions|Descriptions                                                 |initials                          |initials2|New_Description                                                   |
+----------------------------------------------------------------------------------------------+--------------------------+-------------------------------------------------------------+----------------------------------+---------+------------------------------------------------------------------+
|Purchase authorized on 12/05 Qt 296 Inside Lenexa KS\nS582340165832738 Card 3691              |6.42                      |Purchase authorized on 12/05 Qt 296 Inside Lenexa KS         |S582340165832738 Card 3691        |         |Purchase authorized on 12/05 Qt 296 Inside Lenexa KS              |
|Purchase authorized on 12/06 Qt 243 Overland Park KS\nS462340609044917 Card 3691              |5.31                      |Purchase authorized on 12/06 Qt 243 Overland Park KS         |S462340609044917 Card 3691        |         |Purchase authorized on 12/06 Qt 243 Overland Park KS              |
|Purchase authorized on 12/06 Cafe Santa Fe Overland Park KS\nS382340641677396 Card 3691       |4.93                      |Purchase authorized on 12/06 Cafe Santa Fe Overland Park KS  |S382340641677396 Card 3691        |         |Purchase authorized on 12/06 Cafe Santa Fe Overland Park KS       |
|Purchase authorized on 12/06 Qt 296 Inside Lenexa KS\nS382341149520841 Card 3691              |2.07                      |Purchase authorized on 12/06 Qt 296 Inside Lenexa KS         |S382341149520841 Card 3691        |         |Purchase authorized on 12/06 Qt 296 Inside Lenexa KS              |
|Purchase authorized on 12/06 Paypal *Udemy 888-838-5432 CA\nS382341176020450 Card 3691        |11.99                     |Purchase authorized on 12/06 Paypal *Udemy 888-838-5432 CA   |S382341176020450 Card 3691        |         |Purchase authorized on 12/06 Paypal *Udemy 888-838-5432 CA        |
|Purchase authorized on 12/07 Qt 243 Overland Park KS\nS302341594330371 Card 3691              |2.06                      |Purchase authorized on 12/07 Qt 243 Overland Park KS         |S302341594330371 Card 3691        |         |Purchase authorized on 12/07 Qt 243 Overland Park KS              |
|Purchase authorized on 12/08 McDonald's F10543 Overland Park\nKS S302342585515540 Card 3691   |6.2                       |Purchase authorized on 12/08 McDonald's F10543 Overland Park |KS S302342585515540 Card 3691     |KS       |Purchase authorized on 12/08 McDonald's F10543 Overland Park KS   |
|Purchase authorized on 12/08 Superior Mini M Kansas City MO\nP000000785427678 Card 3691       |20.0                      |Purchase authorized on 12/08 Superior Mini M Kansas City MO  |P000000785427678 Card 3691        |         |Purchase authorized on 12/08 Superior Mini M Kansas City MO       |
|Purchase authorized on 12/09 Ross Stores #1696 Overland Park\nKS P000000281059471 Card 3691   |91.31                     |Purchase authorized on 12/09 Ross Stores #1696 Overland Park |KS P000000281059471 Card 3691     |KS       |Purchase authorized on 12/09 Ross Stores #1696 Overland Park KS   |
|Purchase authorized on 12/09 Mk Beauty Supply LLC Overland\nPark KS P302343607792757 Card 3691|13.62                     |Purchase authorized on 12/09 Mk Beauty Supply LLC Overland   |Park KS P302343607792757 Card 3691|Park KS  |Purchase authorized on 12/09 Mk Beauty Supply LLC Overland Park KS|
|Purchase authorized on 12/07 Qt 296 Inside Lenexa KS\nS582342188766791 Card 3691              |2.38                      |Purchase authorized on 12/07 Qt 296 Inside Lenexa KS         |S582342188766791 Card 3691        |         |Purchase authorized on 12/07 Qt 296 Inside Lenexa KS              |
|Purchase authorized on 12/07 Qt 296 Inside Lenexa KS\nS462342189113701 Card 3691              |2.6                       |Purchase authorized on 12/07 Qt 296 Inside Lenexa KS         |S462342189113701 Card 3691        |         |Purchase authorized on 12/07 Qt 296 Inside Lenexa KS              |
|Purchase authorized on 12/08 Qt 296 Inside Lenexa KS\nS582343123191010 Card 3691              |4.67                      |Purchase authorized on 12/08 Qt 296 Inside Lenexa KS         |S582343123191010 Card 3691        |         |Purchase authorized on 12/08 Qt 296 Inside Lenexa KS              |
|Purchase authorized on 12/09 Qt 182 Olathe KS\nS382343537877793 Card 3691                     |5.55                      |Purchase authorized on 12/09 Qt 182 Olathe KS                |S382343537877793 Card 3691        |         |Purchase authorized on 12/09 Qt 182 Olathe KS                     |
|Purchase authorized on 12/09 Cafe Santa Fe Overland Park KS\nS582343730583343 Card 3691       |10.96                     |Purchase authorized on 12/09 Cafe Santa Fe Overland Park KS  |S582343730583343 Card 3691        |         |Purchase authorized on 12/09 Cafe Santa Fe Overland Park KS       |
|Purchase authorized on 12/09 Goodcents Subs - 0 Lenexa KS\nS462343805639077 Card 3691         |13.12                     |Purchase authorized on 12/09 Goodcents Subs - 0 Lenexa KS    |S462343805639077 Card 3691        |         |Purchase authorized on 12/09 Goodcents Subs - 0 Lenexa KS         |
|Purchase authorized on 12/09 Starbucks Store 25 Overland Park\nKS S302343826658285 Card 3691  |3.55                      |Purchase authorized on 12/09 Starbucks Store 25 Overland Park|KS S302343826658285 Card 3691     |KS       |Purchase authorized on 12/09 Starbucks Store 25 Overland Park KS  |
|Purchase authorized on 12/09 Qt 243 Inside Overland Park KS\nP462344133700849 Card 3691       |22.06                     |Purchase authorized on 12/09 Qt 243 Inside Overland Park KS  |P462344133700849 Card 3691        |         |Purchase authorized on 12/09 Qt 243 Inside Overland Park KS       |
|Purchase authorized on 12/10 Qt 206 Olathe KS\nS582344602606138 Card 3691                     |5.44                      |Purchase authorized on 12/10 Qt 206 Olathe KS                |S582344602606138 Card 3691        |         |Purchase authorized on 12/10 Qt 206 Olathe KS                     |
|Purchase authorized on 12/10 Mariscos Kc Olathe KS\nS582344730933940 Card 3691                |23.97                     |Purchase authorized on 12/10 Mariscos Kc Olathe KS           |S582344730933940 Card 3691        |         |Purchase authorized on 12/10 Mariscos Kc Olathe KS                |
+----------------------------------------------------------------------------------------------+--------------------------+-------------------------------------------------------------+----------------------------------+---------+------------------------------------------------------------------+
only showing top 20 rows

In [190]:
#df_pandas_First_filterSplit1_SPARK1.write.format("csv").option("header", "true").mode("overwrite").save("/Pyspark_output.csv")

In [ ]:
from google.colab import files
from google.colab import drive
!pip install openpyxl

In [192]:
pysparkDataFrame_to_Pandas = df_pandas_First_filterSplit1_SPARK1.toPandas()

In [193]:
drive.mount('/content/drive', force_remount=True) 
path = '/content/drive/MyDrive/pysparkDataFrame_to_Pandas.xlsx'
pysparkDataFrame_to_Pandas.to_excel(path, index = None)

Mounted at /content/drive

In [166]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import (col, substring)

In [165]:
string = "Purchase authorized on 12/05"
length = len(string)
print(length)

28

In [167]:
string = "Purchase"
length = len(string)
print(length)

8

In [182]:
# df_pandas_First_filterSplit1_SPARK1.show(truncate=False)
#here we add a new column called 'Transactions' and use substring() to get partial string from 'Descriptions' column
df_pandas_First_filterSplit1_SPARK1.withColumn("Transaction_Date", substring('Descriptions', 1, 28)).show(truncate=False)
df_pandas_First_filterSplit1_SPARK1.withColumn("Transaction", substring('Descriptions', 1, 8)).show(truncate=False)
#df_pandas_First_filterSplit1_SPARK1.withColumn("Transactions", substring('Descriptions', 1, 8)).show(truncate=False)
#df_pandas_First_filterSplit1_SPARK1.withColumn("Transactions", substring('Descriptions', 1, 8)).show(truncate=False)

+----------------------------------------------------------------------------------------------+--------------------------+-------------------------------------------------------------+----------------------------------+---------+----------------------------+
|Description                                                                                   |Withdrawals/\nSubtractions|Descriptions                                                 |initials                          |initials2|Transaction_Date            |
+----------------------------------------------------------------------------------------------+--------------------------+-------------------------------------------------------------+----------------------------------+---------+----------------------------+
|Purchase authorized on 12/05 Qt 296 Inside Lenexa KS\nS582340165832738 Card 3691              |6.42                      |Purchase authorized on 12/05 Qt 296 Inside Lenexa KS         |S582340165832738 Card 3691        |         |Purchase authorized on 12/05|
|Purchase authorized on 12/06 Qt 243 Overland Park KS\nS462340609044917 Card 3691              |5.31                      |Purchase authorized on 12/06 Qt 243 Overland Park KS         |S462340609044917 Card 3691        |         |Purchase authorized on 12/06|
|Purchase authorized on 12/06 Cafe Santa Fe Overland Park KS\nS382340641677396 Card 3691       |4.93                      |Purchase authorized on 12/06 Cafe Santa Fe Overland Park KS  |S382340641677396 Card 3691        |         |Purchase authorized on 12/06|
|Purchase authorized on 12/06 Qt 296 Inside Lenexa KS\nS382341149520841 Card 3691              |2.07                      |Purchase authorized on 12/06 Qt 296 Inside Lenexa KS         |S382341149520841 Card 3691        |         |Purchase authorized on 12/06|
|Purchase authorized on 12/06 Paypal *Udemy 888-838-5432 CA\nS382341176020450 Card 3691        |11.99                     |Purchase authorized on 12/06 Paypal *Udemy 888-838-5432 CA   |S382341176020450 Card 3691        |         |Purchase authorized on 12/06|
|Purchase authorized on 12/07 Qt 243 Overland Park KS\nS302341594330371 Card 3691              |2.06                      |Purchase authorized on 12/07 Qt 243 Overland Park KS         |S302341594330371 Card 3691        |         |Purchase authorized on 12/07|
|Purchase authorized on 12/08 McDonald's F10543 Overland Park\nKS S302342585515540 Card 3691   |6.2                       |Purchase authorized on 12/08 McDonald's F10543 Overland Park |KS S302342585515540 Card 3691     |KS       |Purchase authorized on 12/08|
|Purchase authorized on 12/08 Superior Mini M Kansas City MO\nP000000785427678 Card 3691       |20.0                      |Purchase authorized on 12/08 Superior Mini M Kansas City MO  |P000000785427678 Card 3691        |         |Purchase authorized on 12/08|
|Purchase authorized on 12/09 Ross Stores #1696 Overland Park\nKS P000000281059471 Card 3691   |91.31                     |Purchase authorized on 12/09 Ross Stores #1696 Overland Park |KS P000000281059471 Card 3691     |KS       |Purchase authorized on 12/09|
|Purchase authorized on 12/09 Mk Beauty Supply LLC Overland\nPark KS P302343607792757 Card 3691|13.62                     |Purchase authorized on 12/09 Mk Beauty Supply LLC Overland   |Park KS P302343607792757 Card 3691|Park KS  |Purchase authorized on 12/09|
|Purchase authorized on 12/07 Qt 296 Inside Lenexa KS\nS582342188766791 Card 3691              |2.38                      |Purchase authorized on 12/07 Qt 296 Inside Lenexa KS         |S582342188766791 Card 3691        |         |Purchase authorized on 12/07|
|Purchase authorized on 12/07 Qt 296 Inside Lenexa KS\nS462342189113701 Card 3691              |2.6                       |Purchase authorized on 12/07 Qt 296 Inside Lenexa KS         |S462342189113701 Card 3691        |         |Purchase authorized on 12/07|
|Purchase authorized on 12/08 Qt 296 Inside Lenexa KS\nS582343123191010 Card 3691              |4.67                      |Purchase authorized on 12/08 Qt 296 Inside Lenexa KS         |S582343123191010 Card 3691        |         |Purchase authorized on 12/08|
|Purchase authorized on 12/09 Qt 182 Olathe KS\nS382343537877793 Card 3691                     |5.55                      |Purchase authorized on 12/09 Qt 182 Olathe KS                |S382343537877793 Card 3691        |         |Purchase authorized on 12/09|
|Purchase authorized on 12/09 Cafe Santa Fe Overland Park KS\nS582343730583343 Card 3691       |10.96                     |Purchase authorized on 12/09 Cafe Santa Fe Overland Park KS  |S582343730583343 Card 3691        |         |Purchase authorized on 12/09|
|Purchase authorized on 12/09 Goodcents Subs - 0 Lenexa KS\nS462343805639077 Card 3691         |13.12                     |Purchase authorized on 12/09 Goodcents Subs - 0 Lenexa KS    |S462343805639077 Card 3691        |         |Purchase authorized on 12/09|
|Purchase authorized on 12/09 Starbucks Store 25 Overland Park\nKS S302343826658285 Card 3691  |3.55                      |Purchase authorized on 12/09 Starbucks Store 25 Overland Park|KS S302343826658285 Card 3691     |KS       |Purchase authorized on 12/09|
|Purchase authorized on 12/09 Qt 243 Inside Overland Park KS\nP462344133700849 Card 3691       |22.06                     |Purchase authorized on 12/09 Qt 243 Inside Overland Park KS  |P462344133700849 Card 3691        |         |Purchase authorized on 12/09|
|Purchase authorized on 12/10 Qt 206 Olathe KS\nS582344602606138 Card 3691                     |5.44                      |Purchase authorized on 12/10 Qt 206 Olathe KS                |S582344602606138 Card 3691        |         |Purchase authorized on 12/10|
|Purchase authorized on 12/10 Mariscos Kc Olathe KS\nS582344730933940 Card 3691                |23.97                     |Purchase authorized on 12/10 Mariscos Kc Olathe KS           |S582344730933940 Card 3691        |         |Purchase authorized on 12/10|
+----------------------------------------------------------------------------------------------+--------------------------+-------------------------------------------------------------+----------------------------------+---------+----------------------------+
only showing top 20 rows

+----------------------------------------------------------------------------------------------+--------------------------+-------------------------------------------------------------+----------------------------------+---------+-----------+
|Description                                                                                   |Withdrawals/\nSubtractions|Descriptions                                                 |initials                          |initials2|Transaction|
+----------------------------------------------------------------------------------------------+--------------------------+-------------------------------------------------------------+----------------------------------+---------+-----------+
|Purchase authorized on 12/05 Qt 296 Inside Lenexa KS\nS582340165832738 Card 3691              |6.42                      |Purchase authorized on 12/05 Qt 296 Inside Lenexa KS         |S582340165832738 Card 3691        |         |Purchase   |
|Purchase authorized on 12/06 Qt 243 Overland Park KS\nS462340609044917 Card 3691              |5.31                      |Purchase authorized on 12/06 Qt 243 Overland Park KS         |S462340609044917 Card 3691        |         |Purchase   |
|Purchase authorized on 12/06 Cafe Santa Fe Overland Park KS\nS382340641677396 Card 3691       |4.93                      |Purchase authorized on 12/06 Cafe Santa Fe Overland Park KS  |S382340641677396 Card 3691        |         |Purchase   |
|Purchase authorized on 12/06 Qt 296 Inside Lenexa KS\nS382341149520841 Card 3691              |2.07                      |Purchase authorized on 12/06 Qt 296 Inside Lenexa KS         |S382341149520841 Card 3691        |         |Purchase   |
|Purchase authorized on 12/06 Paypal *Udemy 888-838-5432 CA\nS382341176020450 Card 3691        |11.99                     |Purchase authorized on 12/06 Paypal *Udemy 888-838-5432 CA   |S382341176020450 Card 3691        |         |Purchase   |
|Purchase authorized on 12/07 Qt 243 Overland Park KS\nS302341594330371 Card 3691              |2.06                      |Purchase authorized on 12/07 Qt 243 Overland Park KS         |S302341594330371 Card 3691        |         |Purchase   |
|Purchase authorized on 12/08 McDonald's F10543 Overland Park\nKS S302342585515540 Card 3691   |6.2                       |Purchase authorized on 12/08 McDonald's F10543 Overland Park |KS S302342585515540 Card 3691     |KS       |Purchase   |
|Purchase authorized on 12/08 Superior Mini M Kansas City MO\nP000000785427678 Card 3691       |20.0                      |Purchase authorized on 12/08 Superior Mini M Kansas City MO  |P000000785427678 Card 3691        |         |Purchase   |
|Purchase authorized on 12/09 Ross Stores #1696 Overland Park\nKS P000000281059471 Card 3691   |91.31                     |Purchase authorized on 12/09 Ross Stores #1696 Overland Park |KS P000000281059471 Card 3691     |KS       |Purchase   |
|Purchase authorized on 12/09 Mk Beauty Supply LLC Overland\nPark KS P302343607792757 Card 3691|13.62                     |Purchase authorized on 12/09 Mk Beauty Supply LLC Overland   |Park KS P302343607792757 Card 3691|Park KS  |Purchase   |
|Purchase authorized on 12/07 Qt 296 Inside Lenexa KS\nS582342188766791 Card 3691              |2.38                      |Purchase authorized on 12/07 Qt 296 Inside Lenexa KS         |S582342188766791 Card 3691        |         |Purchase   |
|Purchase authorized on 12/07 Qt 296 Inside Lenexa KS\nS462342189113701 Card 3691              |2.6                       |Purchase authorized on 12/07 Qt 296 Inside Lenexa KS         |S462342189113701 Card 3691        |         |Purchase   |
|Purchase authorized on 12/08 Qt 296 Inside Lenexa KS\nS582343123191010 Card 3691              |4.67                      |Purchase authorized on 12/08 Qt 296 Inside Lenexa KS         |S582343123191010 Card 3691        |         |Purchase   |
|Purchase authorized on 12/09 Qt 182 Olathe KS\nS382343537877793 Card 3691                     |5.55                      |Purchase authorized on 12/09 Qt 182 Olathe KS                |S382343537877793 Card 3691        |         |Purchase   |
|Purchase authorized on 12/09 Cafe Santa Fe Overland Park KS\nS582343730583343 Card 3691       |10.96                     |Purchase authorized on 12/09 Cafe Santa Fe Overland Park KS  |S582343730583343 Card 3691        |         |Purchase   |
|Purchase authorized on 12/09 Goodcents Subs - 0 Lenexa KS\nS462343805639077 Card 3691         |13.12                     |Purchase authorized on 12/09 Goodcents Subs - 0 Lenexa KS    |S462343805639077 Card 3691        |         |Purchase   |
|Purchase authorized on 12/09 Starbucks Store 25 Overland Park\nKS S302343826658285 Card 3691  |3.55                      |Purchase authorized on 12/09 Starbucks Store 25 Overland Park|KS S302343826658285 Card 3691     |KS       |Purchase   |
|Purchase authorized on 12/09 Qt 243 Inside Overland Park KS\nP462344133700849 Card 3691       |22.06                     |Purchase authorized on 12/09 Qt 243 Inside Overland Park KS  |P462344133700849 Card 3691        |         |Purchase   |
|Purchase authorized on 12/10 Qt 206 Olathe KS\nS582344602606138 Card 3691                     |5.44                      |Purchase authorized on 12/10 Qt 206 Olathe KS                |S582344602606138 Card 3691        |         |Purchase   |
|Purchase authorized on 12/10 Mariscos Kc Olathe KS\nS582344730933940 Card 3691                |23.97                     |Purchase authorized on 12/10 Mariscos Kc Olathe KS           |S582344730933940 Card 3691        |         |Purchase   |
+----------------------------------------------------------------------------------------------+--------------------------+-------------------------------------------------------------+----------------------------------+---------+-----------+
only showing top 20 rows

In [185]:
from pyspark.sql.functions import regexp_extract

#spark.createDataFrame([("Purchase authorized on 12/05 Qt 296 Inside Lenexa KS",)], ["text"])
df_pandas_First_filterSplit1_SPARK1.withColumn("Date", regexp_extract(df_pandas_First_filterSplit1_SPARK1["Descriptions"], "(\d{2}/\d{2})", 1)).show(truncate=False)

+----------------------------------------------------------------------------------------------+--------------------------+-------------------------------------------------------------+----------------------------------+---------+-----+
|Description                                                                                   |Withdrawals/\nSubtractions|Descriptions                                                 |initials                          |initials2|Date |
+----------------------------------------------------------------------------------------------+--------------------------+-------------------------------------------------------------+----------------------------------+---------+-----+
|Purchase authorized on 12/05 Qt 296 Inside Lenexa KS\nS582340165832738 Card 3691              |6.42                      |Purchase authorized on 12/05 Qt 296 Inside Lenexa KS         |S582340165832738 Card 3691        |         |12/05|
|Purchase authorized on 12/06 Qt 243 Overland Park KS\nS462340609044917 Card 3691              |5.31                      |Purchase authorized on 12/06 Qt 243 Overland Park KS         |S462340609044917 Card 3691        |         |12/06|
|Purchase authorized on 12/06 Cafe Santa Fe Overland Park KS\nS382340641677396 Card 3691       |4.93                      |Purchase authorized on 12/06 Cafe Santa Fe Overland Park KS  |S382340641677396 Card 3691        |         |12/06|
|Purchase authorized on 12/06 Qt 296 Inside Lenexa KS\nS382341149520841 Card 3691              |2.07                      |Purchase authorized on 12/06 Qt 296 Inside Lenexa KS         |S382341149520841 Card 3691        |         |12/06|
|Purchase authorized on 12/06 Paypal *Udemy 888-838-5432 CA\nS382341176020450 Card 3691        |11.99                     |Purchase authorized on 12/06 Paypal *Udemy 888-838-5432 CA   |S382341176020450 Card 3691        |         |12/06|
|Purchase authorized on 12/07 Qt 243 Overland Park KS\nS302341594330371 Card 3691              |2.06                      |Purchase authorized on 12/07 Qt 243 Overland Park KS         |S302341594330371 Card 3691        |         |12/07|
|Purchase authorized on 12/08 McDonald's F10543 Overland Park\nKS S302342585515540 Card 3691   |6.2                       |Purchase authorized on 12/08 McDonald's F10543 Overland Park |KS S302342585515540 Card 3691     |KS       |12/08|
|Purchase authorized on 12/08 Superior Mini M Kansas City MO\nP000000785427678 Card 3691       |20.0                      |Purchase authorized on 12/08 Superior Mini M Kansas City MO  |P000000785427678 Card 3691        |         |12/08|
|Purchase authorized on 12/09 Ross Stores #1696 Overland Park\nKS P000000281059471 Card 3691   |91.31                     |Purchase authorized on 12/09 Ross Stores #1696 Overland Park |KS P000000281059471 Card 3691     |KS       |12/09|
|Purchase authorized on 12/09 Mk Beauty Supply LLC Overland\nPark KS P302343607792757 Card 3691|13.62                     |Purchase authorized on 12/09 Mk Beauty Supply LLC Overland   |Park KS P302343607792757 Card 3691|Park KS  |12/09|
|Purchase authorized on 12/07 Qt 296 Inside Lenexa KS\nS582342188766791 Card 3691              |2.38                      |Purchase authorized on 12/07 Qt 296 Inside Lenexa KS         |S582342188766791 Card 3691        |         |12/07|
|Purchase authorized on 12/07 Qt 296 Inside Lenexa KS\nS462342189113701 Card 3691              |2.6                       |Purchase authorized on 12/07 Qt 296 Inside Lenexa KS         |S462342189113701 Card 3691        |         |12/07|
|Purchase authorized on 12/08 Qt 296 Inside Lenexa KS\nS582343123191010 Card 3691              |4.67                      |Purchase authorized on 12/08 Qt 296 Inside Lenexa KS         |S582343123191010 Card 3691        |         |12/08|
|Purchase authorized on 12/09 Qt 182 Olathe KS\nS382343537877793 Card 3691                     |5.55                      |Purchase authorized on 12/09 Qt 182 Olathe KS                |S382343537877793 Card 3691        |         |12/09|
|Purchase authorized on 12/09 Cafe Santa Fe Overland Park KS\nS582343730583343 Card 3691       |10.96                     |Purchase authorized on 12/09 Cafe Santa Fe Overland Park KS  |S582343730583343 Card 3691        |         |12/09|
|Purchase authorized on 12/09 Goodcents Subs - 0 Lenexa KS\nS462343805639077 Card 3691         |13.12                     |Purchase authorized on 12/09 Goodcents Subs - 0 Lenexa KS    |S462343805639077 Card 3691        |         |12/09|
|Purchase authorized on 12/09 Starbucks Store 25 Overland Park\nKS S302343826658285 Card 3691  |3.55                      |Purchase authorized on 12/09 Starbucks Store 25 Overland Park|KS S302343826658285 Card 3691     |KS       |12/09|
|Purchase authorized on 12/09 Qt 243 Inside Overland Park KS\nP462344133700849 Card 3691       |22.06                     |Purchase authorized on 12/09 Qt 243 Inside Overland Park KS  |P462344133700849 Card 3691        |         |12/09|
|Purchase authorized on 12/10 Qt 206 Olathe KS\nS582344602606138 Card 3691                     |5.44                      |Purchase authorized on 12/10 Qt 206 Olathe KS                |S582344602606138 Card 3691        |         |12/10|
|Purchase authorized on 12/10 Mariscos Kc Olathe KS\nS582344730933940 Card 3691                |23.97                     |Purchase authorized on 12/10 Mariscos Kc Olathe KS           |S582344730933940 Card 3691        |         |12/10|
+----------------------------------------------------------------------------------------------+--------------------------+-------------------------------------------------------------+----------------------------------+---------+-----+
only showing top 20 rows

In [109]:
#df_pandas_First_filterSplit1_SPARK1["initials"] | States =['KS','Park KS']

In [110]:
list = df_pandas_First_filterSplit1_SPARK1
# Check if the values in 'col1' contain 'KS' or 'Park KS'
#char = ['KS', 'Park KS']
#for c in char:
   #if df_pandas_First_filterSplit1_SPARK1["initials"].str.contains(c):
      # print(df_pandas_First_filterSplit1_SPARK1["initials"])
   #else:
   #print('')

In [111]:
#States =['KS','Park KS']
from pyspark.sql.functions import col

# Convert the "initials" column to a pandas DataFrame
df_initials = df_pandas_First_filterSplit1_SPARK1.select(col("initials")).toPandas()

# Iterate over the values in the "initials" column
for i in df_initials['initials']:
    if i is None:
        print('')
    elif 'Park KS' in i:
        print('Park KS')
    elif 'KS' in i:
        print('KS')
    else:
        print('')

KS

KS
Park KS






KS





KS

















KS
KS


KS



KS


KS


KS











KS








KS











































































KS









Park KS


KS






KS








Park KS




KS

















KS
KS






















KS
















Park KS











KS



Park KS









KS
KS



KS










KS



Park KS




Park KS
KS
Park KS

KS


















KS





KS






KS
KS















KS











Park KS


KS



KS













KS
KS














KS





Park KS

KS












KS
KS







KS


KS
KS













KS
KS
KS



KS


KS



KS


KS

KS





KS
KS


KS
Park KS

KS
KS





KS



KS



KS













KS
KS

KS


KS


KS



KS


KS



KS



KS
KS







KS
KS



KS





KS



KS
KS






KS


KS




KS







KS
KS






KS


KS




KS





KS
KS
Park KS

KS

Park KS
Park KS






KS

KS



















KS

KS





KS
KS

KS











Park KS
KS
KS
KS
KS


KS




KS



KS
Park KS





KS

KS





KS



KS





KS




KS
KS

KS


KS


Park KS


KS

KS


KS

KS


KS



KS



KS
Park KS

KS


KS


KS




KS
KS

KS



KS



KS

KS
KS
KS






KS





KS



KS




KS
KS
KS





KS


KS

KS








KS



KS


KS







KS




KS

KS








KS




KS


KS
















KS






























KS
KS





KS
KS


KS

KS
KS















KS

KS
KS
KS



KS





Park KS

KS
Park KS












KS

KS








KS





KS



KS

KS








KS





KS



Park KS



KS





KS
Park KS



KS






KS



KS



KS










KS
Park KS


KS







KS
KS
KS

















KS





KS



KS
KS
KS









KS






KS
Park KS




KS

KS
KS


KS







KS
KS
KS
KS

KS


KS


KS
KS



KS
KS


KS
Park KS
KS


KS
KS


Park KS
Park KS


Park KS
KS
Park KS
Park KS







KS



KS



KS




KS


KS



KS



KS

In [112]:
df_pandas_First_filterSplit1_SPARK1.select("initials").head()

Row(initials='S582340165832738 Card 3691')

In [113]:
from pyspark.sql.functions import col

filterSplit1_SPARK1 = df_pandas_First_filterSplit1_SPARK1.filter(~col("initials").startswith("S"))

filterSplit1_SPARK1.show()

+--------------------+--------------------------+--------------------+--------------------+
|         Description|Withdrawals/\nSubtractions|        Descriptions|            initials|
+--------------------+--------------------------+--------------------+--------------------+
|Purchase authoriz...|                       6.2|Purchase authoriz...|KS S3023425855155...|
|Purchase authoriz...|                      20.0|Purchase authoriz...|P000000785427678 ...|
|Purchase authoriz...|                     91.31|Purchase authoriz...|KS P0000002810594...|
|Purchase authoriz...|                     13.62|Purchase authoriz...|Park KS P30234360...|
|Purchase authoriz...|                      3.55|Purchase authoriz...|KS S3023438266582...|
|Purchase authoriz...|                     22.06|Purchase authoriz...|P462344133700849 ...|
|Purchase authoriz...|                     22.07|Purchase authoriz...|P302345089974012 ...|
|Purchase authoriz...|                      5.12|Purchase authoriz...|KS P0000001395368...|
|Purchase authoriz...|                     22.07|Purchase authoriz...|P382346001421241 ...|
|Purchase authoriz...|                     27.06|Purchase authoriz...|P382346632782284 ...|
|Purchase authoriz...|                      7.56|Purchase authoriz...|P000000774635445 ...|
|Purchase authoriz...|                      20.0|Purchase authoriz...|P000000081504313 ...|
|Purchase authoriz...|                     22.07|Purchase authoriz...|P382349502000515 ...|
|Purchase authoriz...|                     22.74|Purchase authoriz...|P000000082004895 ...|
|Purchase authoriz...|                      7.91|Purchase authoriz...|P000000570726188 ...|
|Purchase authoriz...|                      20.0|Purchase authoriz...|KS P4623508599709...|
|Purchase authoriz...|                       2.0|Purchase authoriz...|KS S6223514770298...|
|Purchase authoriz...|                      20.0|Purchase authoriz...|KS P4623517629426...|
|Purchase authoriz...|                     24.67|Purchase authoriz...|P582353018052087 ...|
|Purchase authoriz...|                      5.65|Purchase authoriz...|KS S5823536754334...|
+--------------------+--------------------------+--------------------+--------------------+
only showing top 20 rows

In [114]:
filterSplit1_SPARK2 = df_pandas_First_filterSplit1_SPARK1.filter(~col("initials").startswith("KS"))

filterSplit1_SPARK2.show()

+--------------------+--------------------------+--------------------+--------------------+
|         Description|Withdrawals/\nSubtractions|        Descriptions|            initials|
+--------------------+--------------------------+--------------------+--------------------+
|Purchase authoriz...|                      6.42|Purchase authoriz...|S582340165832738 ...|
|Purchase authoriz...|                      5.31|Purchase authoriz...|S462340609044917 ...|
|Purchase authoriz...|                      4.93|Purchase authoriz...|S382340641677396 ...|
|Purchase authoriz...|                      2.07|Purchase authoriz...|S382341149520841 ...|
|Purchase authoriz...|                     11.99|Purchase authoriz...|S382341176020450 ...|
|Purchase authoriz...|                      2.06|Purchase authoriz...|S302341594330371 ...|
|Purchase authoriz...|                      20.0|Purchase authoriz...|P000000785427678 ...|
|Purchase authoriz...|                     13.62|Purchase authoriz...|Park KS P30234360...|
|Purchase authoriz...|                      2.38|Purchase authoriz...|S582342188766791 ...|
|Purchase authoriz...|                       2.6|Purchase authoriz...|S462342189113701 ...|
|Purchase authoriz...|                      4.67|Purchase authoriz...|S582343123191010 ...|
|Purchase authoriz...|                      5.55|Purchase authoriz...|S382343537877793 ...|
|Purchase authoriz...|                     10.96|Purchase authoriz...|S582343730583343 ...|
|Purchase authoriz...|                     13.12|Purchase authoriz...|S462343805639077 ...|
|Purchase authoriz...|                     22.06|Purchase authoriz...|P462344133700849 ...|
|Purchase authoriz...|                      5.44|Purchase authoriz...|S582344602606138 ...|
|Purchase authoriz...|                     23.97|Purchase authoriz...|S582344730933940 ...|
|Purchase authoriz...|                      5.11|Purchase authoriz...|S582345004221906 ...|
|Purchase authoriz...|                     22.07|Purchase authoriz...|P302345089974012 ...|
|Purchase authoriz...|                     22.07|Purchase authoriz...|P382346001421241 ...|
+--------------------+--------------------------+--------------------+--------------------+
only showing top 20 rows

In [115]:
filterSplit1_SPARK3 = df_pandas_First_filterSplit1_SPARK1.filter(~col("initials").startswith("Park KS"))

filterSplit1_SPARK3.show()

+--------------------+--------------------------+--------------------+--------------------+
|         Description|Withdrawals/\nSubtractions|        Descriptions|            initials|
+--------------------+--------------------------+--------------------+--------------------+
|Purchase authoriz...|                      6.42|Purchase authoriz...|S582340165832738 ...|
|Purchase authoriz...|                      5.31|Purchase authoriz...|S462340609044917 ...|
|Purchase authoriz...|                      4.93|Purchase authoriz...|S382340641677396 ...|
|Purchase authoriz...|                      2.07|Purchase authoriz...|S382341149520841 ...|
|Purchase authoriz...|                     11.99|Purchase authoriz...|S382341176020450 ...|
|Purchase authoriz...|                      2.06|Purchase authoriz...|S302341594330371 ...|
|Purchase authoriz...|                       6.2|Purchase authoriz...|KS S3023425855155...|
|Purchase authoriz...|                      20.0|Purchase authoriz...|P000000785427678 ...|
|Purchase authoriz...|                     91.31|Purchase authoriz...|KS P0000002810594...|
|Purchase authoriz...|                      2.38|Purchase authoriz...|S582342188766791 ...|
|Purchase authoriz...|                       2.6|Purchase authoriz...|S462342189113701 ...|
|Purchase authoriz...|                      4.67|Purchase authoriz...|S582343123191010 ...|
|Purchase authoriz...|                      5.55|Purchase authoriz...|S382343537877793 ...|
|Purchase authoriz...|                     10.96|Purchase authoriz...|S582343730583343 ...|
|Purchase authoriz...|                     13.12|Purchase authoriz...|S462343805639077 ...|
|Purchase authoriz...|                      3.55|Purchase authoriz...|KS S3023438266582...|
|Purchase authoriz...|                     22.06|Purchase authoriz...|P462344133700849 ...|
|Purchase authoriz...|                      5.44|Purchase authoriz...|S582344602606138 ...|
|Purchase authoriz...|                     23.97|Purchase authoriz...|S582344730933940 ...|
|Purchase authoriz...|                      5.11|Purchase authoriz...|S582345004221906 ...|
+--------------------+--------------------------+--------------------+--------------------+
only showing top 20 rows

In [116]:
filter_KS_KSPark = df_pandas_First_filterSplit1_SPARK1.filter(~(col("initials").rlike("KS|Park KS")))
filter_KS_KSPark.show(truncate=False)

+---------------------------------------------------------------------------------------+--------------------------+-----------------------------------------------------------+--------------------------+
|Description                                                                            |Withdrawals/\nSubtractions|Descriptions                                               |initials                  |
+---------------------------------------------------------------------------------------+--------------------------+-----------------------------------------------------------+--------------------------+
|Purchase authorized on 12/05 Qt 296 Inside Lenexa KS\nS582340165832738 Card 3691       |6.42                      |Purchase authorized on 12/05 Qt 296 Inside Lenexa KS       |S582340165832738 Card 3691|
|Purchase authorized on 12/06 Qt 243 Overland Park KS\nS462340609044917 Card 3691       |5.31                      |Purchase authorized on 12/06 Qt 243 Overland Park KS       |S462340609044917 Card 3691|
|Purchase authorized on 12/06 Cafe Santa Fe Overland Park KS\nS382340641677396 Card 3691|4.93                      |Purchase authorized on 12/06 Cafe Santa Fe Overland Park KS|S382340641677396 Card 3691|
|Purchase authorized on 12/06 Qt 296 Inside Lenexa KS\nS382341149520841 Card 3691       |2.07                      |Purchase authorized on 12/06 Qt 296 Inside Lenexa KS       |S382341149520841 Card 3691|
|Purchase authorized on 12/06 Paypal *Udemy 888-838-5432 CA\nS382341176020450 Card 3691 |11.99                     |Purchase authorized on 12/06 Paypal *Udemy 888-838-5432 CA |S382341176020450 Card 3691|
|Purchase authorized on 12/07 Qt 243 Overland Park KS\nS302341594330371 Card 3691       |2.06                      |Purchase authorized on 12/07 Qt 243 Overland Park KS       |S302341594330371 Card 3691|
|Purchase authorized on 12/08 Superior Mini M Kansas City MO\nP000000785427678 Card 3691|20.0                      |Purchase authorized on 12/08 Superior Mini M Kansas City MO|P000000785427678 Card 3691|
|Purchase authorized on 12/07 Qt 296 Inside Lenexa KS\nS582342188766791 Card 3691       |2.38                      |Purchase authorized on 12/07 Qt 296 Inside Lenexa KS       |S582342188766791 Card 3691|
|Purchase authorized on 12/07 Qt 296 Inside Lenexa KS\nS462342189113701 Card 3691       |2.6                       |Purchase authorized on 12/07 Qt 296 Inside Lenexa KS       |S462342189113701 Card 3691|
|Purchase authorized on 12/08 Qt 296 Inside Lenexa KS\nS582343123191010 Card 3691       |4.67                      |Purchase authorized on 12/08 Qt 296 Inside Lenexa KS       |S582343123191010 Card 3691|
|Purchase authorized on 12/09 Qt 182 Olathe KS\nS382343537877793 Card 3691              |5.55                      |Purchase authorized on 12/09 Qt 182 Olathe KS              |S382343537877793 Card 3691|
|Purchase authorized on 12/09 Cafe Santa Fe Overland Park KS\nS582343730583343 Card 3691|10.96                     |Purchase authorized on 12/09 Cafe Santa Fe Overland Park KS|S582343730583343 Card 3691|
|Purchase authorized on 12/09 Goodcents Subs - 0 Lenexa KS\nS462343805639077 Card 3691  |13.12                     |Purchase authorized on 12/09 Goodcents Subs - 0 Lenexa KS  |S462343805639077 Card 3691|
|Purchase authorized on 12/09 Qt 243 Inside Overland Park KS\nP462344133700849 Card 3691|22.06                     |Purchase authorized on 12/09 Qt 243 Inside Overland Park KS|P462344133700849 Card 3691|
|Purchase authorized on 12/10 Qt 206 Olathe KS\nS582344602606138 Card 3691              |5.44                      |Purchase authorized on 12/10 Qt 206 Olathe KS              |S582344602606138 Card 3691|
|Purchase authorized on 12/10 Mariscos Kc Olathe KS\nS582344730933940 Card 3691         |23.97                     |Purchase authorized on 12/10 Mariscos Kc Olathe KS         |S582344730933940 Card 3691|
|Purchase authorized on 12/10 Qt 235 Lenexa KS\nS582345004221906 Card 3691              |5.11                      |Purchase authorized on 12/10 Qt 235 Lenexa KS              |S582345004221906 Card 3691|
|Purchase authorized on 12/10 Qt 296 Inside Lenexa KS\nP302345089974012 Card 3691       |22.07                     |Purchase authorized on 12/10 Qt 296 Inside Lenexa KS       |P302345089974012 Card 3691|
|Purchase authorized on 12/11 Qt 235 Inside Lenexa KS\nP382346001421241 Card 3691       |22.07                     |Purchase authorized on 12/11 Qt 235 Inside Lenexa KS       |P382346001421241 Card 3691|
|Purchase authorized on 12/12 Qt 235 Inside Lenexa KS\nP382346632782284 Card 3691       |27.06                     |Purchase authorized on 12/12 Qt 235 Inside Lenexa KS       |P382346632782284 Card 3691|
+---------------------------------------------------------------------------------------+--------------------------+-----------------------------------------------------------+--------------------------+
only showing top 20 rows

In [117]:
second_filter = spark_df.filter(~(spark_df.Description).like("Purchase authorized on%"))

In [118]:
#second_filterSPL = second_filter.withColumn("Identi", f.split(second_filter['Description'], '\\')[1]).\
                                # withColumn("Actions", f.split(second_filter['Description'], '\\')[0])

#second_filterSPL.show(truncate=False)

In [119]:
second_filter = spark_df.filter(~(spark_df.Description).like("Purchase authorized on%")) #or.show()
second_filter.show(truncate=False)

+-------------------------------------------------------------------------------------------------------------------+--------------------------+
|Description                                                                                                        |Withdrawals/\nSubtractions|
+-------------------------------------------------------------------------------------------------------------------+--------------------------+
|Wells Fargo Card Reserve 221209 60004 90154503061186                                                               |233.0                     |
|Non-WF ATM Withdrawal authorized on 12/10 203 N Marion St\nOlathe KS 302344735023921 ATM ID 210260 Card 3691       |43.0                      |
|Doordash, Inc. Doordash, St-M0H2Q9F3H1W9 Yedou Lare                                                                |NaN                       |
|Recurring Payment authorized on 12/13 Affirm * Pay Oc57B\n855-423-3729 CA S302347682837327 Card 3691               |148.26                    |
|Riamoneytransfer Cust Trans 221214 US983482418 Yedou Lare                                                          |54.0                      |
|Recurring Payment authorized on 12/15 American Family Mu\n608-242-4100 WI S462349437323873 Card 7563               |71.85                     |
|Planet Fit Club Fees 2235002086146 913-402-0999                                                                    |10.91                     |
|Best Buy Payment 221218 630934817235853 Yedou Lare                                                                 |60.15                     |
|Doordash, Inc. Doordash, St-C9W8S1U1L5J0 Yedou Lare                                                                |NaN                       |
|Non-WF ATM Withdrawal authorized on 12/23 10301 W 75th St\nShawnee Missi KS 462357586623405 ATM ID Um3185 Card 3691|33.0                      |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Doordash, Inc. Doordash, St-H2R7x8B7U8I6 Yedou Lare                                                                |NaN                       |
|Uber USA 6787 EDI Paymnt Jan 02 Lap4Eaf8C3J2Tiv\nRef*TN*Lap4Eaf8C3\                                                |NaN                       |
|Doordash, Inc. Doordash, St-U2Q5N4R3M9x2 Yedou Lare                                                                |NaN                       |
|Non-WF ATM Withdrawal authorized on 01/04 Quiktrip #636\nSaint Louis MO 583004675340359 ATM ID Sve21883 Card 3691  |43.0                      |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Doordash, Inc. Doordash, St-T1G5A1P1I2U7 Yedou Lare                                                                |NaN                       |
|Purchase with Cash Back $ 20.00 authorized on 11/13 Price\nChopper 6 Overland Par KS P000000284514352 Card 3691    |32.42                     |
|Recurring Payment authorized on 11/13 Affirm * Pay Lgrf2\n855-423-3729 CA S302317670893516 Card 3691               |148.26                    |
|Doordash, Inc. Doordash, St-Y8T4W3L3G1E4 Yedou Lare                                                                |NaN                       |
+-------------------------------------------------------------------------------------------------------------------+--------------------------+
only showing top 20 rows

In [120]:
DROPNA = second_filter.na.drop()
DROPNA.show(truncate=False)

+-------------------------------------------------------------------------------------------------------------------+--------------------------+
|Description                                                                                                        |Withdrawals/\nSubtractions|
+-------------------------------------------------------------------------------------------------------------------+--------------------------+
|Wells Fargo Card Reserve 221209 60004 90154503061186                                                               |233.0                     |
|Non-WF ATM Withdrawal authorized on 12/10 203 N Marion St\nOlathe KS 302344735023921 ATM ID 210260 Card 3691       |43.0                      |
|Recurring Payment authorized on 12/13 Affirm * Pay Oc57B\n855-423-3729 CA S302347682837327 Card 3691               |148.26                    |
|Riamoneytransfer Cust Trans 221214 US983482418 Yedou Lare                                                          |54.0                      |
|Recurring Payment authorized on 12/15 American Family Mu\n608-242-4100 WI S462349437323873 Card 7563               |71.85                     |
|Planet Fit Club Fees 2235002086146 913-402-0999                                                                    |10.91                     |
|Best Buy Payment 221218 630934817235853 Yedou Lare                                                                 |60.15                     |
|Non-WF ATM Withdrawal authorized on 12/23 10301 W 75th St\nShawnee Missi KS 462357586623405 ATM ID Um3185 Card 3691|33.0                      |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Non-WF ATM Withdrawal authorized on 01/04 Quiktrip #636\nSaint Louis MO 583004675340359 ATM ID Sve21883 Card 3691  |43.0                      |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Purchase with Cash Back $ 20.00 authorized on 11/13 Price\nChopper 6 Overland Par KS P000000284514352 Card 3691    |32.42                     |
|Recurring Payment authorized on 11/13 Affirm * Pay Lgrf2\n855-423-3729 CA S302317670893516 Card 3691               |148.26                    |
|Recurring Payment authorized on 11/15 American Family Mu\n608-242-4100 WI S462319438330821 Card 7563               |71.85                     |
|Planet Fit Club Fees 2232001780320 913-402-0999                                                                    |10.91                     |
|Best Buy Payment 221118 630909522617074 Yedou Lare                                                                 |50.18                     |
|Cash eWithdrawal in Branch/Store 12/03/2022 07:02 Am 12000 W\n95th St Lenexa KS 3691                               |400.0                     |
|ATM Withdrawal authorized on 12/04 11809 Shawnee Mission\nPkw Shawnee KS 0009449 ATM ID 0307F Card 3691            |100.0                     |
|Wells Fargo Card Reserve 221011 60001 90154503061186                                                               |96.0                      |
|Non-WF ATM Withdrawal authorized on 10/12 3500 Sante Lenexa\nKS 382285544144052 ATM ID 525041 Card 3691            |22.99                     |
+-------------------------------------------------------------------------------------------------------------------+--------------------------+
only showing top 20 rows

In [121]:
# https://sqlandhadoop.com/pyspark-filter-25-examples-to-teach-you-everything/
from pandas.core.arrays.interval import isin
from pyspark.sql.functions import col
#droplist = ["Wells Fargo Card Reserve","Recurring Payment authorized on","Riamoneytransfer Cust Trans","Best Buy Payment"]

T_filter1 = DROPNA.filter(col("Description").like("Wells Fargo Card Reserve%"))
T_filter1.show(truncate=False)

+----------------------------------------------------+--------------------------+
|Description                                         |Withdrawals/\nSubtractions|
+----------------------------------------------------+--------------------------+
|Wells Fargo Card Reserve 221209 60004 90154503061186|233.0                     |
|Wells Fargo Card Reserve 221011 60001 90154503061186|96.0                      |
|Wells Fargo Card Reserve 221018 60002 90154503061186|139.0                     |
|Wells Fargo Card Reserve 221022 60003 90154503061186|142.0                     |
+----------------------------------------------------+--------------------------+

In [122]:
T_filter2 = DROPNA.filter(col("Description").like("Recurring Payment authorized on%"))
T_filter2.show(truncate=False)

+----------------------------------------------------------------------------------------------------+--------------------------+
|Description                                                                                         |Withdrawals/\nSubtractions|
+----------------------------------------------------------------------------------------------------+--------------------------+
|Recurring Payment authorized on 12/13 Affirm * Pay Oc57B\n855-423-3729 CA S302347682837327 Card 3691|148.26                    |
|Recurring Payment authorized on 12/15 American Family Mu\n608-242-4100 WI S462349437323873 Card 7563|71.85                     |
|Recurring Payment authorized on 11/13 Affirm * Pay Lgrf2\n855-423-3729 CA S302317670893516 Card 3691|148.26                    |
|Recurring Payment authorized on 11/15 American Family Mu\n608-242-4100 WI S462319438330821 Card 7563|71.85                     |
|Recurring Payment authorized on 10/13 Affirm * Pay Doi93\n855-423-3729 CA S302286683500400 Card 3691|148.26                    |
|Recurring Payment authorized on 10/15 American Family Mu\n608-242-4100 WI S382288400448527 Card 7563|71.85                     |
|Recurring Payment authorized on 09/13 Affirm * Pay Uv8Kp\n855-423-3729 CA S582256666727090 Card 3691|148.26                    |
|Recurring Payment authorized on 09/15 American Family Mu\n608-242-4100 WI S382258401351848 Card 7563|71.85                     |
|Recurring Payment authorized on 10/01 Paypal *Linkedin\n402-935-7733 CA S302274532903518 Card 3691  |29.99                     |
|Recurring Payment authorized on 08/13 Affirm * Pay 5Phqt\n855-423-3729 CA S582225665189398 Card 3691|148.26                    |
|Recurring Payment authorized on 08/15 American Family Mu\n608-242-4100 WI S582227397578574 Card 7563|68.55                     |
|Recurring Payment authorized on 09/01 Paypal *Linkedin\n402-935-7733 CA S462244533155865 Card 3691  |29.99                     |
|Recurring Payment authorized on 07/13 Affirm * Pay Jb6Ci\n855-423-3729 CA S462194692080603 Card 3691|148.26                    |
|Recurring Payment authorized on 07/15 American Family Mu\n608-242-4100 WI S462196453038767 Card 7563|68.54                     |
|Recurring Payment authorized on 08/01 Paypal *Linkedin\n402-935-7733 CA S302213532904297 Card 3691  |29.99                     |
|Recurring Payment authorized on 06/15 American Family Mu\n608-242-4100 WI S462166399177336 Card 7563|78.92                     |
|Recurring Payment authorized on 07/01 Paypal *Linkedin\n402-935-7733 CA S302182532949929 Card 3691  |29.99                     |
|Recurring Payment authorized on 07/01 Paypal *Linkedin\n402-935-7733 CA S302182532949929 Card 3691  |29.99                     |
|Recurring Payment authorized on 05/15 American Family Mu\n608-242-4100 WI S582135399357851 Card 7563|78.92                     |
|Recurring Payment authorized on 06/01 Paypal *Linkedin\n402-935-7733 CA S382152532960614 Card 3691  |29.99                     |
+----------------------------------------------------------------------------------------------------+--------------------------+
only showing top 20 rows

In [123]:
T_filter3 = DROPNA.filter(col("Description").like("Riamoneytransfer Cust Trans%"))
T_filter3.show(truncate=False)

+---------------------------------------------------------+--------------------------+
|Description                                              |Withdrawals/\nSubtractions|
+---------------------------------------------------------+--------------------------+
|Riamoneytransfer Cust Trans 221214 US983482418 Yedou Lare|54.0                      |
|Riamoneytransfer Cust Trans 221026 US458578518 Yedou Lare|54.0                      |
+---------------------------------------------------------+--------------------------+

In [124]:
T_filter4 = DROPNA.filter(col("Description").like("Best Buy Payment%"))
T_filter4.show(truncate=False)

+--------------------------------------------------+--------------------------+
|Description                                       |Withdrawals/\nSubtractions|
+--------------------------------------------------+--------------------------+
|Best Buy Payment 221218 630934817235853 Yedou Lare|60.15                     |
|Best Buy Payment 221118 630909522617074 Yedou Lare|50.18                     |
|Best Buy Payment 221017 620882703356071 Yedou Lare|32.21                     |
|Best Buy Payment 220916 600855696834482 Yedou Lare|46.24                     |
|Best Buy Payment 220817 630829459139693 Yedou Lare|32.28                     |
|Best Buy Payment 220714 600799903529497 Yedou Lare|40.0                      |
|Best Buy Payment 220617 630776715354652 Yedou Lare|29.0                      |
|Best Buy Payment 220517 630749848081774 Yedou Lare|29.0                      |
|Best Buy Payment 220417 630723797499309 Yedou Lare|42.0                      |
|Best Buy Payment 220317 630697218882924 Yedou Lare|29.0                      |
|Best Buy Payment 220217 620673008640480 Yedou Lare|29.0                      |
|Best Buy Payment 220110 630640710421642 Yedou Lare|29.0                      |
+--------------------------------------------------+--------------------------+

In [125]:
T_filter5 = DROPNA.filter(col("Description").like("Monthly Service Fee%"))
T_filter5.show(truncate=False)

+-------------------+--------------------------+
|Description        |Withdrawals/\nSubtractions|
+-------------------+--------------------------+
|Monthly Service Fee|15.0                      |
+-------------------+--------------------------+

In [126]:
# filter(col(“product_title”).rlike(“^(Reebok|Nike)(.*)+$”))
#T_filter5 = DROPNA.filter(~col("Description").rlike("^(Wells Fargo Card Reserve|Best Buy Payment |Riamoneytransfer Cust Trans|Recurring Payment authorized on)(.*)+$"))
#T_filter5.show(truncate=False)

In [127]:
# Wells Fargo Card Reserve|Best Buy Payment |Riamoneytransfer Cust Trans|Recurring Payment authorized on
#T_filter6 = DROPNA.filter(~col("Description").like("Wells Fargo Card Reserve%")|col("Description").like("Best Buy Payment%")|col("Description").like("Riamoneytransfer Cust Trans%")|col("Description").like("Recurring Payment authorized on%"))
#T_filter6.show(truncate=False)

In [128]:
T_filter7 = DROPNA.filter(~col("Description").contains("Wells Fargo Card Reserve"))
T_filter7.show(truncate=False)

+-------------------------------------------------------------------------------------------------------------------+--------------------------+
|Description                                                                                                        |Withdrawals/\nSubtractions|
+-------------------------------------------------------------------------------------------------------------------+--------------------------+
|Non-WF ATM Withdrawal authorized on 12/10 203 N Marion St\nOlathe KS 302344735023921 ATM ID 210260 Card 3691       |43.0                      |
|Recurring Payment authorized on 12/13 Affirm * Pay Oc57B\n855-423-3729 CA S302347682837327 Card 3691               |148.26                    |
|Riamoneytransfer Cust Trans 221214 US983482418 Yedou Lare                                                          |54.0                      |
|Recurring Payment authorized on 12/15 American Family Mu\n608-242-4100 WI S462349437323873 Card 7563               |71.85                     |
|Planet Fit Club Fees 2235002086146 913-402-0999                                                                    |10.91                     |
|Best Buy Payment 221218 630934817235853 Yedou Lare                                                                 |60.15                     |
|Non-WF ATM Withdrawal authorized on 12/23 10301 W 75th St\nShawnee Missi KS 462357586623405 ATM ID Um3185 Card 3691|33.0                      |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Non-WF ATM Withdrawal authorized on 01/04 Quiktrip #636\nSaint Louis MO 583004675340359 ATM ID Sve21883 Card 3691  |43.0                      |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Purchase with Cash Back $ 20.00 authorized on 11/13 Price\nChopper 6 Overland Par KS P000000284514352 Card 3691    |32.42                     |
|Recurring Payment authorized on 11/13 Affirm * Pay Lgrf2\n855-423-3729 CA S302317670893516 Card 3691               |148.26                    |
|Recurring Payment authorized on 11/15 American Family Mu\n608-242-4100 WI S462319438330821 Card 7563               |71.85                     |
|Planet Fit Club Fees 2232001780320 913-402-0999                                                                    |10.91                     |
|Best Buy Payment 221118 630909522617074 Yedou Lare                                                                 |50.18                     |
|Cash eWithdrawal in Branch/Store 12/03/2022 07:02 Am 12000 W\n95th St Lenexa KS 3691                               |400.0                     |
|ATM Withdrawal authorized on 12/04 11809 Shawnee Mission\nPkw Shawnee KS 0009449 ATM ID 0307F Card 3691            |100.0                     |
|Non-WF ATM Withdrawal authorized on 10/12 3500 Sante Lenexa\nKS 382285544144052 ATM ID 525041 Card 3691            |22.99                     |
|Planet Fit Club Fees 2228702453328 913-402-0999                                                                    |10.91                     |
|Recurring Payment authorized on 10/13 Affirm * Pay Doi93\n855-423-3729 CA S302286683500400 Card 3691               |148.26                    |
+-------------------------------------------------------------------------------------------------------------------+--------------------------+
only showing top 20 rows

In [129]:
T_filter8 = T_filter7.filter(~col("Description").contains("Recurring Payment authorized on"))
T_filter8.show(truncate=False)

+-------------------------------------------------------------------------------------------------------------------+--------------------------+
|Description                                                                                                        |Withdrawals/\nSubtractions|
+-------------------------------------------------------------------------------------------------------------------+--------------------------+
|Non-WF ATM Withdrawal authorized on 12/10 203 N Marion St\nOlathe KS 302344735023921 ATM ID 210260 Card 3691       |43.0                      |
|Riamoneytransfer Cust Trans 221214 US983482418 Yedou Lare                                                          |54.0                      |
|Planet Fit Club Fees 2235002086146 913-402-0999                                                                    |10.91                     |
|Best Buy Payment 221218 630934817235853 Yedou Lare                                                                 |60.15                     |
|Non-WF ATM Withdrawal authorized on 12/23 10301 W 75th St\nShawnee Missi KS 462357586623405 ATM ID Um3185 Card 3691|33.0                      |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Non-WF ATM Withdrawal authorized on 01/04 Quiktrip #636\nSaint Louis MO 583004675340359 ATM ID Sve21883 Card 3691  |43.0                      |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Purchase with Cash Back $ 20.00 authorized on 11/13 Price\nChopper 6 Overland Par KS P000000284514352 Card 3691    |32.42                     |
|Planet Fit Club Fees 2232001780320 913-402-0999                                                                    |10.91                     |
|Best Buy Payment 221118 630909522617074 Yedou Lare                                                                 |50.18                     |
|Cash eWithdrawal in Branch/Store 12/03/2022 07:02 Am 12000 W\n95th St Lenexa KS 3691                               |400.0                     |
|ATM Withdrawal authorized on 12/04 11809 Shawnee Mission\nPkw Shawnee KS 0009449 ATM ID 0307F Card 3691            |100.0                     |
|Non-WF ATM Withdrawal authorized on 10/12 3500 Sante Lenexa\nKS 382285544144052 ATM ID 525041 Card 3691            |22.99                     |
|Planet Fit Club Fees 2228702453328 913-402-0999                                                                    |10.91                     |
|Best Buy Payment 221017 620882703356071 Yedou Lare                                                                 |32.21                     |
|Non-WF ATM Withdrawal authorized on 10/20 1051 W Dennis\nAve. Olathe KS 382293861968744 ATM ID Um3252 Card 3691    |63.0                      |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Online Transfer Ref #Ib0Gpxhy33 to Platinum Card\nXxxxxxxxxxxx1186 on 10/22/22                                     |142.0                     |
|Riamoneytransfer Cust Trans 221026 US458578518 Yedou Lare                                                          |54.0                      |
+-------------------------------------------------------------------------------------------------------------------+--------------------------+
only showing top 20 rows

In [130]:
T_filter9 = T_filter8.filter(~col("Description").contains("Best Buy Payment"))
T_filter9.show(truncate=False)

+-------------------------------------------------------------------------------------------------------------------+--------------------------+
|Description                                                                                                        |Withdrawals/\nSubtractions|
+-------------------------------------------------------------------------------------------------------------------+--------------------------+
|Non-WF ATM Withdrawal authorized on 12/10 203 N Marion St\nOlathe KS 302344735023921 ATM ID 210260 Card 3691       |43.0                      |
|Riamoneytransfer Cust Trans 221214 US983482418 Yedou Lare                                                          |54.0                      |
|Planet Fit Club Fees 2235002086146 913-402-0999                                                                    |10.91                     |
|Non-WF ATM Withdrawal authorized on 12/23 10301 W 75th St\nShawnee Missi KS 462357586623405 ATM ID Um3185 Card 3691|33.0                      |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Non-WF ATM Withdrawal authorized on 01/04 Quiktrip #636\nSaint Louis MO 583004675340359 ATM ID Sve21883 Card 3691  |43.0                      |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Purchase with Cash Back $ 20.00 authorized on 11/13 Price\nChopper 6 Overland Par KS P000000284514352 Card 3691    |32.42                     |
|Planet Fit Club Fees 2232001780320 913-402-0999                                                                    |10.91                     |
|Cash eWithdrawal in Branch/Store 12/03/2022 07:02 Am 12000 W\n95th St Lenexa KS 3691                               |400.0                     |
|ATM Withdrawal authorized on 12/04 11809 Shawnee Mission\nPkw Shawnee KS 0009449 ATM ID 0307F Card 3691            |100.0                     |
|Non-WF ATM Withdrawal authorized on 10/12 3500 Sante Lenexa\nKS 382285544144052 ATM ID 525041 Card 3691            |22.99                     |
|Planet Fit Club Fees 2228702453328 913-402-0999                                                                    |10.91                     |
|Non-WF ATM Withdrawal authorized on 10/20 1051 W Dennis\nAve. Olathe KS 382293861968744 ATM ID Um3252 Card 3691    |63.0                      |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Online Transfer Ref #Ib0Gpxhy33 to Platinum Card\nXxxxxxxxxxxx1186 on 10/22/22                                     |142.0                     |
|Riamoneytransfer Cust Trans 221026 US458578518 Yedou Lare                                                          |54.0                      |
|Non-WF ATM Withdrawal authorized on 11/01 1051 W Dennis\nAve. Olathe KS 582305639904156 ATM ID Um3252 Card 3691    |163.0                     |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Planet Fit Club Fees 2225901942479 913-402-0999                                                                    |10.91                     |
+-------------------------------------------------------------------------------------------------------------------+--------------------------+
only showing top 20 rows

In [131]:
T_filter10 = T_filter9.filter(~col("Description").contains("Riamoneytransfer Cust Trans"))
T_filter10.show(truncate=False)

+-------------------------------------------------------------------------------------------------------------------+--------------------------+
|Description                                                                                                        |Withdrawals/\nSubtractions|
+-------------------------------------------------------------------------------------------------------------------+--------------------------+
|Non-WF ATM Withdrawal authorized on 12/10 203 N Marion St\nOlathe KS 302344735023921 ATM ID 210260 Card 3691       |43.0                      |
|Planet Fit Club Fees 2235002086146 913-402-0999                                                                    |10.91                     |
|Non-WF ATM Withdrawal authorized on 12/23 10301 W 75th St\nShawnee Missi KS 462357586623405 ATM ID Um3185 Card 3691|33.0                      |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Non-WF ATM Withdrawal authorized on 01/04 Quiktrip #636\nSaint Louis MO 583004675340359 ATM ID Sve21883 Card 3691  |43.0                      |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Purchase with Cash Back $ 20.00 authorized on 11/13 Price\nChopper 6 Overland Par KS P000000284514352 Card 3691    |32.42                     |
|Planet Fit Club Fees 2232001780320 913-402-0999                                                                    |10.91                     |
|Cash eWithdrawal in Branch/Store 12/03/2022 07:02 Am 12000 W\n95th St Lenexa KS 3691                               |400.0                     |
|ATM Withdrawal authorized on 12/04 11809 Shawnee Mission\nPkw Shawnee KS 0009449 ATM ID 0307F Card 3691            |100.0                     |
|Non-WF ATM Withdrawal authorized on 10/12 3500 Sante Lenexa\nKS 382285544144052 ATM ID 525041 Card 3691            |22.99                     |
|Planet Fit Club Fees 2228702453328 913-402-0999                                                                    |10.91                     |
|Non-WF ATM Withdrawal authorized on 10/20 1051 W Dennis\nAve. Olathe KS 382293861968744 ATM ID Um3252 Card 3691    |63.0                      |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Online Transfer Ref #Ib0Gpxhy33 to Platinum Card\nXxxxxxxxxxxx1186 on 10/22/22                                     |142.0                     |
|Non-WF ATM Withdrawal authorized on 11/01 1051 W Dennis\nAve. Olathe KS 582305639904156 ATM ID Um3252 Card 3691    |163.0                     |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Planet Fit Club Fees 2225901942479 913-402-0999                                                                    |10.91                     |
|Non-WF ATM Withdrawal authorized on 10/07 1051 W Dennis\nAve. Olathe KS 382280546082627 ATM ID Um3252 Card 3691    |53.0                      |
|Monthly Service Fee                                                                                                |15.0                      |
+-------------------------------------------------------------------------------------------------------------------+--------------------------+
only showing top 20 rows

In [132]:
# Monthly Service Fee
T_filter11 = T_filter10.filter(~col("Description").contains("Monthly Service Fee"))
T_filter11.show(truncate=False)

+-------------------------------------------------------------------------------------------------------------------+--------------------------+
|Description                                                                                                        |Withdrawals/\nSubtractions|
+-------------------------------------------------------------------------------------------------------------------+--------------------------+
|Non-WF ATM Withdrawal authorized on 12/10 203 N Marion St\nOlathe KS 302344735023921 ATM ID 210260 Card 3691       |43.0                      |
|Planet Fit Club Fees 2235002086146 913-402-0999                                                                    |10.91                     |
|Non-WF ATM Withdrawal authorized on 12/23 10301 W 75th St\nShawnee Missi KS 462357586623405 ATM ID Um3185 Card 3691|33.0                      |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Non-WF ATM Withdrawal authorized on 01/04 Quiktrip #636\nSaint Louis MO 583004675340359 ATM ID Sve21883 Card 3691  |43.0                      |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Purchase with Cash Back $ 20.00 authorized on 11/13 Price\nChopper 6 Overland Par KS P000000284514352 Card 3691    |32.42                     |
|Planet Fit Club Fees 2232001780320 913-402-0999                                                                    |10.91                     |
|Cash eWithdrawal in Branch/Store 12/03/2022 07:02 Am 12000 W\n95th St Lenexa KS 3691                               |400.0                     |
|ATM Withdrawal authorized on 12/04 11809 Shawnee Mission\nPkw Shawnee KS 0009449 ATM ID 0307F Card 3691            |100.0                     |
|Non-WF ATM Withdrawal authorized on 10/12 3500 Sante Lenexa\nKS 382285544144052 ATM ID 525041 Card 3691            |22.99                     |
|Planet Fit Club Fees 2228702453328 913-402-0999                                                                    |10.91                     |
|Non-WF ATM Withdrawal authorized on 10/20 1051 W Dennis\nAve. Olathe KS 382293861968744 ATM ID Um3252 Card 3691    |63.0                      |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Online Transfer Ref #Ib0Gpxhy33 to Platinum Card\nXxxxxxxxxxxx1186 on 10/22/22                                     |142.0                     |
|Non-WF ATM Withdrawal authorized on 11/01 1051 W Dennis\nAve. Olathe KS 582305639904156 ATM ID Um3252 Card 3691    |163.0                     |
|Non-Wells Fargo ATM Transaction Fee                                                                                |2.5                       |
|Planet Fit Club Fees 2225901942479 913-402-0999                                                                    |10.91                     |
|Non-WF ATM Withdrawal authorized on 10/07 1051 W Dennis\nAve. Olathe KS 382280546082627 ATM ID Um3252 Card 3691    |53.0                      |
|Planet Fit Club Fees 2222801379879 913-402-0999                                                                    |10.91                     |
+-------------------------------------------------------------------------------------------------------------------+--------------------------+
only showing top 20 rows

In [133]:
df_pandas_T_filter11= T_filter11.toPandas()
df_pandas_T_filter11

,Description,Withdrawals/\nSubtractions
0,Non-WF ATM Withdrawal authorized on 12/10 203 ...,43.00
1,Planet Fit Club Fees 2235002086146 913-402-0999,10.91
2,Non-WF ATM Withdrawal authorized on 12/23 1030...,33.00
3,Non-Wells Fargo ATM Transaction Fee,2.50
4,Non-WF ATM Withdrawal authorized on 01/04 Quik...,43.00
5,Non-Wells Fargo ATM Transaction Fee,2.50
6,Purchase with Cash Back $ 20.00 authorized on ...,32.42
7,Planet Fit Club Fees 2232001780320 913-402-0999,10.91
8,Cash eWithdrawal in Branch/Store 12/03/2022 07...,400.00
9,ATM Withdrawal authorized on 12/04 11809 Shawn...,100.00
10,Non-WF ATM Withdrawal authorized on 10/12 3500...,22.99
11,Planet Fit Club Fees 2228702453328 913-402-0999,10.91
12,Non-WF ATM Withdrawal authorized on 10/20 1051...,63.00
13,Non-Wells Fargo ATM Transaction Fee,2.50
14,Online Transfer Ref #Ib0Gpxhy33 to Platinum Ca...,142.00
15,Non-WF ATM Withdrawal authorized on 11/01 1051...,163.00
16,Non-Wells Fargo ATM Transaction Fee,2.50
17,Planet Fit Club Fees 2225901942479 913-402-0999,10.91
18,Non-WF ATM Withdrawal authorized on 10/07 1051...,53.00
19,Planet Fit Club Fees 2222801379879 913-402-0999,10.91
20,Planet Fit Club Fees 2219602003293 913-402-0999,10.91
21,Online Transfer Ref #Ib0Fwhxbsk to Platinum Ca...,97.00
22,Non-WF ATM Balance Inquiry Fee 06/14 917S Park...,2.50
23,Non-WF ATM Withdrawal authorized on 06/14 917S...,62.99
24,Planet Fit Club Fees 2216701262500 913-402-0999,10.91
25,Online Transfer Ref #Ib0Fndmtcg to Platinum Ca...,94.00
26,Purchase with Cash Back $ 60.00 authorized on ...,368.00
27,Non-WF ATM Withdrawal authorized on 06/29 1051...,43.00
28,Non-Wells Fargo ATM Transaction Fee,2.50
29,Non-WF ATM Balance Inquiry Fee 06/30 917S Park...,2.50
30,Non-WF ATM Balance Inquiry Fee 06/30 917S Park...,2.50
31,Purchase with Cash Back $ 60.00 authorized on ...,368.00
32,Non-WF ATM Withdrawal authorized on 06/29 1051...,43.00
33,Non-Wells Fargo ATM Transaction Fee,2.50
34,Non-WF ATM Balance Inquiry Fee 06/30 917S Park...,2.50
35,Non-WF ATM Balance Inquiry Fee 06/30 917S Park...,2.50
36,ATM Withdrawal authorized on 07/05 2137 E Sant...,40.00
37,Non-WF ATM Balance Inquiry Fee 07/06 395 N K-7...,2.50
38,Purchase with Cash Back $ 100.00 authorized on...,2316.00
39,Planet Fit Club Fees 2213601122288 913-402-0999,10.91
40,Online Transfer Ref #Ib0Fdw6Grj to Platinum Ca...,93.00
41,Planet Fit Club Fees 2215100274378 913-402-0999,31.45
42,ATM Withdrawal authorized on 04/12 2137 E Sant...,20.00
43,ATM Withdrawal authorized on 04/12 2137 E Sant...,150.00
44,ATM Withdrawal authorized on 04/14 11809 Shawn...,50.00
45,Planet Fit Club Fees 2210501733692 913-402-0999,10.91
46,Online Transfer Ref #Ib0F5Bp9Tm to Platinum Ca...,97.00
47,Purchase with Cash Back $ 208.32 authorized on...,286.72
48,Planet Fit Club Fees 2207501342306 913-402-0999,10.91
49,Online Transfer Ref #Ib0Dw2Tzpd to Platinum Ca...,131.00
50,Non-WF ATM Withdrawal authorized on 04/02 1550...,23.50
51,Cash eWithdrawal in Branch/Store 04/05/2022 09...,2000.00
52,Non-WF ATM Withdrawal authorized on 04/02 1550...,23.50
53,Cash eWithdrawal in Branch/Store 04/05/2022 09...,2000.00
54,Non-WF ATM Withdrawal authorized on 02/16 1051...,23.00
55,Planet Fit Club Fees 2204701271844 913-402-0999,10.91
56,Online Transfer Ref #Ib0Dnfjd9V to Platinum Ca...,96.00
57,Planet Fit Club Fees 2201401518133 913-402-0999,10.91
58,Online Transfer Ref #Ib0Df5Ksh4 to Platinum Ca...,132.00
59,Non-WF ATM Withdrawal authorized on 02/04 8150...,63.00

In [134]:
T_filter12 = T_filter11.filter(col("Description").contains("Non-WF ATM Withdrawal authorized on"))
T_filter12.show(truncate=False)

+---------------------------------------------------------------------------------------------------------------------------+--------------------------+
|Description                                                                                                                |Withdrawals/\nSubtractions|
+---------------------------------------------------------------------------------------------------------------------------+--------------------------+
|Non-WF ATM Withdrawal authorized on 12/10 203 N Marion St\nOlathe KS 302344735023921 ATM ID 210260 Card 3691               |43.0                      |
|Non-WF ATM Withdrawal authorized on 12/23 10301 W 75th St\nShawnee Missi KS 462357586623405 ATM ID Um3185 Card 3691        |33.0                      |
|Non-WF ATM Withdrawal authorized on 01/04 Quiktrip #636\nSaint Louis MO 583004675340359 ATM ID Sve21883 Card 3691          |43.0                      |
|Non-WF ATM Withdrawal authorized on 10/12 3500 Sante Lenexa\nKS 382285544144052 ATM ID 525041 Card 3691                    |22.99                     |
|Non-WF ATM Withdrawal authorized on 10/20 1051 W Dennis\nAve. Olathe KS 382293861968744 ATM ID Um3252 Card 3691            |63.0                      |
|Non-WF ATM Withdrawal authorized on 11/01 1051 W Dennis\nAve. Olathe KS 582305639904156 ATM ID Um3252 Card 3691            |163.0                     |
|Non-WF ATM Withdrawal authorized on 10/07 1051 W Dennis\nAve. Olathe KS 382280546082627 ATM ID Um3252 Card 3691            |53.0                      |
|Non-WF ATM Withdrawal authorized on 06/14 917S Parker\nOlather KS 302166001917102 ATM ID 556618 Card 3691                  |62.99                     |
|Non-WF ATM Withdrawal authorized on 06/29 1051 W Dennis\nAve. Olathe KS 302180847936481 ATM ID Um3252 Card 3691            |43.0                      |
|Non-WF ATM Withdrawal authorized on 06/29 1051 W Dennis\nAve. Olathe KS 302180847936481 ATM ID Um3252 Card 3691            |43.0                      |
|Non-WF ATM Withdrawal authorized on 04/02 1550 S Hamilton\nCir Olathe KS 382093082045661 ATM ID 7E007112 Card 3691         |23.5                      |
|Non-WF ATM Withdrawal authorized on 04/02 1550 S Hamilton\nCir Olathe KS 382093082045661 ATM ID 7E007112 Card 3691         |23.5                      |
|Non-WF ATM Withdrawal authorized on 02/16 1051 W Dennis\nAve. Olathe KS 382047682938508 ATM ID Um3252 Card 3691            |23.0                      |
|Non-WF ATM Withdrawal authorized on 02/04 8150 NW Prairie View Ro Kansas City MO 302035841674670 ATM ID NH109377\nCard 3691|63.0                      |
+---------------------------------------------------------------------------------------------------------------------------+--------------------------+

In [135]:
df_pandas_T_filter12= T_filter12.toPandas()
df_pandas_T_filter12

,Description,Withdrawals/\nSubtractions
0,Non-WF ATM Withdrawal authorized on 12/10 203 ...,43.00
1,Non-WF ATM Withdrawal authorized on 12/23 1030...,33.00
2,Non-WF ATM Withdrawal authorized on 01/04 Quik...,43.00
3,Non-WF ATM Withdrawal authorized on 10/12 3500...,22.99
4,Non-WF ATM Withdrawal authorized on 10/20 1051...,63.00
5,Non-WF ATM Withdrawal authorized on 11/01 1051...,163.00
6,Non-WF ATM Withdrawal authorized on 10/07 1051...,53.00
7,Non-WF ATM Withdrawal authorized on 06/14 917S...,62.99
8,Non-WF ATM Withdrawal authorized on 06/29 1051...,43.00
9,Non-WF ATM Withdrawal authorized on 06/29 1051...,43.00
10,Non-WF ATM Withdrawal authorized on 04/02 1550...,23.50
11,Non-WF ATM Withdrawal authorized on 04/02 1550...,23.50
12,Non-WF ATM Withdrawal authorized on 02/16 1051...,23.00
13,Non-WF ATM Withdrawal authorized on 02/04 8150...,63.00

In [136]:
T_filter13 = T_filter11.filter(col("Description").contains("Planet Fit Club Fees"))
T_filter13.show(truncate=False)

+-----------------------------------------------+--------------------------+
|Description                                    |Withdrawals/\nSubtractions|
+-----------------------------------------------+--------------------------+
|Planet Fit Club Fees 2235002086146 913-402-0999|10.91                     |
|Planet Fit Club Fees 2232001780320 913-402-0999|10.91                     |
|Planet Fit Club Fees 2228702453328 913-402-0999|10.91                     |
|Planet Fit Club Fees 2225901942479 913-402-0999|10.91                     |
|Planet Fit Club Fees 2222801379879 913-402-0999|10.91                     |
|Planet Fit Club Fees 2219602003293 913-402-0999|10.91                     |
|Planet Fit Club Fees 2216701262500 913-402-0999|10.91                     |
|Planet Fit Club Fees 2213601122288 913-402-0999|10.91                     |
|Planet Fit Club Fees 2215100274378 913-402-0999|31.45                     |
|Planet Fit Club Fees 2210501733692 913-402-0999|10.91                     |
|Planet Fit Club Fees 2207501342306 913-402-0999|10.91                     |
|Planet Fit Club Fees 2204701271844 913-402-0999|10.91                     |
|Planet Fit Club Fees 2201401518133 913-402-0999|10.91                     |
+-----------------------------------------------+--------------------------+

In [137]:
df_pandas_T_filter13= T_filter13.toPandas()
df_pandas_T_filter13

,Description,Withdrawals/\nSubtractions
0,Planet Fit Club Fees 2235002086146 913-402-0999,10.91
1,Planet Fit Club Fees 2232001780320 913-402-0999,10.91
2,Planet Fit Club Fees 2228702453328 913-402-0999,10.91
3,Planet Fit Club Fees 2225901942479 913-402-0999,10.91
4,Planet Fit Club Fees 2222801379879 913-402-0999,10.91
5,Planet Fit Club Fees 2219602003293 913-402-0999,10.91
6,Planet Fit Club Fees 2216701262500 913-402-0999,10.91
7,Planet Fit Club Fees 2213601122288 913-402-0999,10.91
8,Planet Fit Club Fees 2215100274378 913-402-0999,31.45
9,Planet Fit Club Fees 2210501733692 913-402-0999,10.91
10,Planet Fit Club Fees 2207501342306 913-402-0999,10.91
11,Planet Fit Club Fees 2204701271844 913-402-0999,10.91
12,Planet Fit Club Fees 2201401518133 913-402-0999,10.91

In [138]:
T_filter14 = T_filter11.filter(col("Description").contains("Non-Wells Fargo ATM Transaction Fee"))
T_filter14.show(truncate=False)

+-----------------------------------+--------------------------+
|Description                        |Withdrawals/\nSubtractions|
+-----------------------------------+--------------------------+
|Non-Wells Fargo ATM Transaction Fee|2.5                       |
|Non-Wells Fargo ATM Transaction Fee|2.5                       |
|Non-Wells Fargo ATM Transaction Fee|2.5                       |
|Non-Wells Fargo ATM Transaction Fee|2.5                       |
|Non-Wells Fargo ATM Transaction Fee|2.5                       |
|Non-Wells Fargo ATM Transaction Fee|2.5                       |
+-----------------------------------+--------------------------+

In [139]:
df_pandas_T_filter14= T_filter14.toPandas()
df_pandas_T_filter14

                           Description  Withdrawals/\nSubtractions
0  Non-Wells Fargo ATM Transaction Fee                         2.5
1  Non-Wells Fargo ATM Transaction Fee                         2.5
2  Non-Wells Fargo ATM Transaction Fee                         2.5
3  Non-Wells Fargo ATM Transaction Fee                         2.5
4  Non-Wells Fargo ATM Transaction Fee                         2.5
5  Non-Wells Fargo ATM Transaction Fee                         2.5

In [140]:
T_filter15 = T_filter11.filter(col("Description").contains("Cash eWithdrawal"))
T_filter15.show(truncate=False)

+------------------------------------------------------------------------------------+--------------------------+
|Description                                                                         |Withdrawals/\nSubtractions|
+------------------------------------------------------------------------------------+--------------------------+
|Cash eWithdrawal in Branch/Store 12/03/2022 07:02 Am 12000 W\n95th St Lenexa KS 3691|400.0                     |
|Cash eWithdrawal in Branch/Store 04/05/2022 09:05 Am 12000 W\n95th St Lenexa KS 3691|2000.0                    |
|Cash eWithdrawal in Branch/Store 04/05/2022 09:05 Am 12000 W\n95th St Lenexa KS 3691|2000.0                    |
+------------------------------------------------------------------------------------+--------------------------+

In [141]:
df_pandas_T_filter15= T_filter15.toPandas()
df_pandas_T_filter15

,Description,Withdrawals/\nSubtractions
0,Cash eWithdrawal in Branch/Store 12/03/2022 07...,400.0
1,Cash eWithdrawal in Branch/Store 04/05/2022 09...,2000.0
2,Cash eWithdrawal in Branch/Store 04/05/2022 09...,2000.0

In [142]:
T_filter16 = T_filter11.filter(col("Description").contains("Online Transfer Ref #"))
T_filter16.show(truncate=False)

+------------------------------------------------------------------------------+--------------------------+
|Description                                                                   |Withdrawals/\nSubtractions|
+------------------------------------------------------------------------------+--------------------------+
|Online Transfer Ref #Ib0Gpxhy33 to Platinum Card\nXxxxxxxxxxxx1186 on 10/22/22|142.0                     |
|Online Transfer Ref #Ib0Fwhxbsk to Platinum Card\nXxxxxxxxxxxx1186 on 07/21/22|97.0                      |
|Online Transfer Ref #Ib0Fndmtcg to Platinum Card\nXxxxxxxxxxxx1186 on 06/22/22|94.0                      |
|Online Transfer Ref #Ib0Fdw6Grj to Platinum Card\nXxxxxxxxxxxx1186 on 05/22/22|93.0                      |
|Online Transfer Ref #Ib0F5Bp9Tm to Platinum Card\nXxxxxxxxxxxx1186 on 04/21/22|97.0                      |
|Online Transfer Ref #Ib0Dw2Tzpd to Platinum Card\nXxxxxxxxxxxx1186 on 03/22/22|131.0                     |
|Online Transfer Ref #Ib0Dnfjd9V to Platinum Card\nXxxxxxxxxxxx1186 on 02/23/22|96.0                      |
|Online Transfer Ref #Ib0Df5Ksh4 to Platinum Card\nXxxxxxxxxxxx1186 on 01/21/22|132.0                     |
+------------------------------------------------------------------------------+--------------------------+

In [143]:
df_pandas_T_filter16= T_filter16.toPandas()
df_pandas_T_filter16

,Description,Withdrawals/\nSubtractions
0,Online Transfer Ref #Ib0Gpxhy33 to Platinum Ca...,142.0
1,Online Transfer Ref #Ib0Fwhxbsk to Platinum Ca...,97.0
2,Online Transfer Ref #Ib0Fndmtcg to Platinum Ca...,94.0
3,Online Transfer Ref #Ib0Fdw6Grj to Platinum Ca...,93.0
4,Online Transfer Ref #Ib0F5Bp9Tm to Platinum Ca...,97.0
5,Online Transfer Ref #Ib0Dw2Tzpd to Platinum Ca...,131.0
6,Online Transfer Ref #Ib0Dnfjd9V to Platinum Ca...,96.0
7,Online Transfer Ref #Ib0Df5Ksh4 to Platinum Ca...,132.0

In [144]:
#df = df.filter(~col("col").rlike("abc") & ~col("col").like("%x%"))
#df = df.filter(~(col("col").rlike("abc") | col("col").like("%x%")))

In [145]:
dfremain1 = T_filter11.filter(~(col("Description").rlike("Wells Fargo Card Reserve|Recurring Payment authorized on|Riamoneytransfer Cust Trans|Best Buy Payment|Non-WF ATM Withdrawal authorized on|Planet Fit Club Fees|Non-Wells Fargo ATM Transaction Fee|Cash eWithdrawal|Online Transfer Ref #")))
dfremain1.show(truncate=False)

+----------------------------------------------------------------------------------------------------------------------+--------------------------+
|Description                                                                                                           |Withdrawals/\nSubtractions|
+----------------------------------------------------------------------------------------------------------------------+--------------------------+
|Purchase with Cash Back $ 20.00 authorized on 11/13 Price\nChopper 6 Overland Par KS P000000284514352 Card 3691       |32.42                     |
|ATM Withdrawal authorized on 12/04 11809 Shawnee Mission\nPkw Shawnee KS 0009449 ATM ID 0307F Card 3691               |100.0                     |
|Non-WF ATM Balance Inquiry Fee 06/14 917S Parker Olather KS\nATM ID 556618 Card 3691                                  |2.5                       |
|Purchase with Cash Back $ 60.00 authorized on 06/29 WM Superc\nWal-Mart Sup Olathe KS P000000571647241 Card 3691      |368.0                     |
|Non-WF ATM Balance Inquiry Fee 06/30 917S Parker Olather KS\nATM ID 556618 Card 3691                                  |2.5                       |
|Non-WF ATM Balance Inquiry Fee 06/30 917S Parker Olather KS\nATM ID 556618 Card 3691                                  |2.5                       |
|Purchase with Cash Back $ 60.00 authorized on 06/29 WM Superc\nWal-Mart Sup Olathe KS P000000571647241 Card 3691      |368.0                     |
|Non-WF ATM Balance Inquiry Fee 06/30 917S Parker Olather KS\nATM ID 556618 Card 3691                                  |2.5                       |
|Non-WF ATM Balance Inquiry Fee 06/30 917S Parker Olather KS\nATM ID 556618 Card 3691                                  |2.5                       |
|ATM Withdrawal authorized on 07/05 2137 E Santa Fe Dr Olathe\nKS 0008334 ATM ID 0586Y Card 3691                       |40.0                      |
|Non-WF ATM Balance Inquiry Fee 07/06 395 N K-7 HI Olathe KS\nATM ID T5306473 Card 3691                                |2.5                       |
|Purchase with Cash Back $ 100.00 authorized on 07/07 Wal-Mart\nWal-Mart Sto Northlake IL P000000877469893 Card 3691   |2316.0                    |
|ATM Withdrawal authorized on 04/12 2137 E Santa Fe Dr Olathe\nKS 0008955 ATM ID 0586Y Card 3691                       |20.0                      |
|ATM Withdrawal authorized on 04/12 2137 E Santa Fe Dr Olathe\nKS 0008956 ATM ID 0586Y Card 3691                       |150.0                     |
|ATM Withdrawal authorized on 04/14 11809 Shawnee Mission\nPkw Shawnee KS 0007554 ATM ID 0307F Card 3691               |50.0                      |
|Purchase with Cash Back $ 208.32 authorized on 03/16 USPS PO\n19863505 19800 ME Stilwell KS P582075564917998 Card 3691|286.72                    |
+----------------------------------------------------------------------------------------------------------------------+--------------------------+

In [146]:
dfremain1pd1= dfremain1.toPandas()
dfremain1pd1

,Description,Withdrawals/\nSubtractions
0,Purchase with Cash Back $ 20.00 authorized on ...,32.42
1,ATM Withdrawal authorized on 12/04 11809 Shawn...,100.00
2,Non-WF ATM Balance Inquiry Fee 06/14 917S Park...,2.50
3,Purchase with Cash Back $ 60.00 authorized on ...,368.00
4,Non-WF ATM Balance Inquiry Fee 06/30 917S Park...,2.50
5,Non-WF ATM Balance Inquiry Fee 06/30 917S Park...,2.50
6,Purchase with Cash Back $ 60.00 authorized on ...,368.00
7,Non-WF ATM Balance Inquiry Fee 06/30 917S Park...,2.50
8,Non-WF ATM Balance Inquiry Fee 06/30 917S Park...,2.50
9,ATM Withdrawal authorized on 07/05 2137 E Sant...,40.00
10,Non-WF ATM Balance Inquiry Fee 07/06 395 N K-7...,2.50
11,Purchase with Cash Back $ 100.00 authorized on...,2316.00
12,ATM Withdrawal authorized on 04/12 2137 E Sant...,20.00
13,ATM Withdrawal authorized on 04/12 2137 E Sant...,150.00
14,ATM Withdrawal authorized on 04/14 11809 Shawn...,50.00
15,Purchase with Cash Back $ 208.32 authorized on...,286.72

In [147]:
####################################################################################
T_filter17 = dfremain1.filter(col("Description").like("Purchase with Cash Back $%"))
T_filter17.show(truncate=False)

+----------------------------------------------------------------------------------------------------------------------+--------------------------+
|Description                                                                                                           |Withdrawals/\nSubtractions|
+----------------------------------------------------------------------------------------------------------------------+--------------------------+
|Purchase with Cash Back $ 20.00 authorized on 11/13 Price\nChopper 6 Overland Par KS P000000284514352 Card 3691       |32.42                     |
|Purchase with Cash Back $ 60.00 authorized on 06/29 WM Superc\nWal-Mart Sup Olathe KS P000000571647241 Card 3691      |368.0                     |
|Purchase with Cash Back $ 60.00 authorized on 06/29 WM Superc\nWal-Mart Sup Olathe KS P000000571647241 Card 3691      |368.0                     |
|Purchase with Cash Back $ 100.00 authorized on 07/07 Wal-Mart\nWal-Mart Sto Northlake IL P000000877469893 Card 3691   |2316.0                    |
|Purchase with Cash Back $ 208.32 authorized on 03/16 USPS PO\n19863505 19800 ME Stilwell KS P582075564917998 Card 3691|286.72                    |
+----------------------------------------------------------------------------------------------------------------------+--------------------------+

In [148]:
T_filter18 = dfremain1.filter(col("Description").like("ATM Withdrawal authorized on%"))
T_filter18.show(truncate=False)

+-------------------------------------------------------------------------------------------------------+--------------------------+
|Description                                                                                            |Withdrawals/\nSubtractions|
+-------------------------------------------------------------------------------------------------------+--------------------------+
|ATM Withdrawal authorized on 12/04 11809 Shawnee Mission\nPkw Shawnee KS 0009449 ATM ID 0307F Card 3691|100.0                     |
|ATM Withdrawal authorized on 07/05 2137 E Santa Fe Dr Olathe\nKS 0008334 ATM ID 0586Y Card 3691        |40.0                      |
|ATM Withdrawal authorized on 04/12 2137 E Santa Fe Dr Olathe\nKS 0008955 ATM ID 0586Y Card 3691        |20.0                      |
|ATM Withdrawal authorized on 04/12 2137 E Santa Fe Dr Olathe\nKS 0008956 ATM ID 0586Y Card 3691        |150.0                     |
|ATM Withdrawal authorized on 04/14 11809 Shawnee Mission\nPkw Shawnee KS 0007554 ATM ID 0307F Card 3691|50.0                      |
+-------------------------------------------------------------------------------------------------------+--------------------------+

In [149]:
T_filter19 = dfremain1.filter(col("Description").like("Non-WF ATM Balance Inquiry Fee %"))
T_filter19.show(truncate=False)

+--------------------------------------------------------------------------------------+--------------------------+
|Description                                                                           |Withdrawals/\nSubtractions|
+--------------------------------------------------------------------------------------+--------------------------+
|Non-WF ATM Balance Inquiry Fee 06/14 917S Parker Olather KS\nATM ID 556618 Card 3691  |2.5                       |
|Non-WF ATM Balance Inquiry Fee 06/30 917S Parker Olather KS\nATM ID 556618 Card 3691  |2.5                       |
|Non-WF ATM Balance Inquiry Fee 06/30 917S Parker Olather KS\nATM ID 556618 Card 3691  |2.5                       |
|Non-WF ATM Balance Inquiry Fee 06/30 917S Parker Olather KS\nATM ID 556618 Card 3691  |2.5                       |
|Non-WF ATM Balance Inquiry Fee 06/30 917S Parker Olather KS\nATM ID 556618 Card 3691  |2.5                       |
|Non-WF ATM Balance Inquiry Fee 07/06 395 N K-7 HI Olathe KS\nATM ID T5306473 Card 3691|2.5                       |
+--------------------------------------------------------------------------------------+--------------------------+

In [150]:
dfremain2 = T_filter19.filter(~(col("Description").rlike("Non-WF ATM Balance Inquiry Fee|ATM Withdrawal authorized on|Purchase with Cash Back $")))
dfremain2.show(truncate=False)

+-----------+--------------------------+
|Description|Withdrawals/\nSubtractions|
+-----------+--------------------------+
+-----------+--------------------------+

In [151]:
#from pyspark.sql.functions import replace

# create a sample dataframe
#df = spark.createDataFrame([("Purchase authorized on 12/05 Qt 296 Inside Lenexa KS\nS582340165832738 Card 3691",)], ["text"])

# replace the unwanted text with an empty string
#df = df.withColumn("text", replace(df["text"], "Purchase authorized on 12/05 Qt 296 Inside Lenexa KS\n", ""))

In [152]:
#from pyspark.sql.functions import substring

# create a sample dataframe
#df = spark.createDataFrame([("Purchase authorized on 12/05 Qt 296 Inside Lenexa KS\nS582340165832738 Card 3691",)], ["text"])

# keep only the desired text
#df = df.withColumn("text", substring(df["text"], 0, 44))